# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
foreach(width IN ITEMS 8 16 32)
  if(width EQUAL 32)
    set(symbol bf16_dot2)
    set(register zmm)
    set(wider_register "unavailable-register")
  elseif(width EQUAL 16)
    set(symbol bf16_dot2_16)
    set(register ymm)
    set(wider_register zmm)
  else()
    set(symbol bf16_dot2_8)
    set(register xmm)
    set(wider_register "[yz]mm")
  endif()
  execute_process(COMMAND "${OBJDUMP}" -d --no-show-raw-insn "--disassemble-symbols=${symbol}" "${OBJECT}"
    RESULT_VARIABLE status OUTPUT_VARIABLE assembly ERROR_VARIABLE errors)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "objdump failed: ${errors}")
  endif()
  string(REGEX MATCHALL "vdpbf16ps" instructions "${assembly}")
  list(LENGTH instructions count)
  if(NOT count EQUAL 1 OR NOT assembly MATCHES "vdpbf16ps[^\n]*${register}")
    message(FATAL_ERROR "Expected one native ${register} BF16 dot instruction: ${assembly}")
  endif()
  if(assembly MATCHES "[ \t]call[q]?[ \t]|${wider_register}|vcvt|vfmadd|vmulps|vaddps")
    message(FATAL_ERROR "Unexpected call, widening, conversion or FP32 emulation: ${assembly}")
  endif()
  message(STATUS "${symbol} uses one ${register} VDPBF16PS without widening or calls")
endforeach()
