// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
namespace crypto_fixture {
  template<native::isa A, class T0, class T1> concept available_aes_0 = requires(T0 a0, T1 a1) { native::aese<A>(a0, a1); };
  static_assert(available_aes_0<native::isa{native::arm_feature::aes}, uint8x16_t, uint8x16_t>);
  static_assert(!available_aes_0<native::scalar, uint8x16_t, uint8x16_t>);
  static_assert(!available_aes_0<native::isa{native::arm_feature::aes}, float64x2_t, uint8x16_t>);
  template<native::isa A, class T0, class T1> concept available_aes_1 = requires(T0 a0, T1 a1) { native::aesd<A>(a0, a1); };
  static_assert(available_aes_1<native::isa{native::arm_feature::aes}, uint8x16_t, uint8x16_t>);
  static_assert(!available_aes_1<native::scalar, uint8x16_t, uint8x16_t>);
  static_assert(!available_aes_1<native::isa{native::arm_feature::aes}, float64x2_t, uint8x16_t>);
  template<native::isa A, class T0> concept available_aes_2 = requires(T0 a0) { native::aesmc<A>(a0); };
  static_assert(available_aes_2<native::isa{native::arm_feature::aes}, uint8x16_t>);
  static_assert(!available_aes_2<native::scalar, uint8x16_t>);
  static_assert(!available_aes_2<native::isa{native::arm_feature::aes}, float64x2_t>);
  template<native::isa A, class T0> concept available_aes_3 = requires(T0 a0) { native::aesimc<A>(a0); };
  static_assert(available_aes_3<native::isa{native::arm_feature::aes}, uint8x16_t>);
  static_assert(!available_aes_3<native::scalar, uint8x16_t>);
  static_assert(!available_aes_3<native::isa{native::arm_feature::aes}, float64x2_t>);
  template<native::isa A, class T0, class T1> concept available_pmull_0 = requires(T0 a0, T1 a1) { native::pmull<A>(a0, a1); };
  static_assert(available_pmull_0<native::isa{native::arm_feature::pmull}, poly64_t, poly64_t>);
  static_assert(!available_pmull_0<native::scalar, poly64_t, poly64_t>);
  static_assert(!available_pmull_0<native::isa{native::arm_feature::pmull}, double, poly64_t>);
  template<native::isa A, class T0, class T1> concept available_pmull_1 = requires(T0 a0, T1 a1) { native::pmull2<A>(a0, a1); };
  static_assert(available_pmull_1<native::isa{native::arm_feature::pmull}, poly64x2_t, poly64x2_t>);
  static_assert(!available_pmull_1<native::scalar, poly64x2_t, poly64x2_t>);
  static_assert(!available_pmull_1<native::isa{native::arm_feature::pmull}, uint64x2_t, poly64x2_t>);
  template<native::isa A, class T0, class T1> concept available_pmull_2 = requires(T0 a0, T1 a1) { native::pmull<A>(a0, a1); };
  static_assert(available_pmull_2<native::isa{native::arm_feature::neon}, poly8x8_t, poly8x8_t>);
  static_assert(!available_pmull_2<native::scalar, poly8x8_t, poly8x8_t>);
  static_assert(!available_pmull_2<native::isa{native::arm_feature::neon}, float64x2_t, poly8x8_t>);
  template<native::isa A, class T0, class T1> concept available_pmull_3 = requires(T0 a0, T1 a1) { native::pmull2<A>(a0, a1); };
  static_assert(available_pmull_3<native::isa{native::arm_feature::neon}, poly8x16_t, poly8x16_t>);
  static_assert(!available_pmull_3<native::scalar, poly8x16_t, poly8x16_t>);
  static_assert(!available_pmull_3<native::isa{native::arm_feature::neon}, float64x2_t, poly8x16_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_0 = requires(T0 a0, T1 a1, T2 a2) { native::sha1c<A>(a0, a1, a2); };
  static_assert(available_sha_0<native::isa{native::arm_feature::sha1}, uint32x4_t, std::uint32_t, uint32x4_t>);
  static_assert(!available_sha_0<native::scalar, uint32x4_t, std::uint32_t, uint32x4_t>);
  static_assert(!available_sha_0<native::isa{native::arm_feature::sha1}, float64x2_t, std::uint32_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_1 = requires(T0 a0, T1 a1, T2 a2) { native::sha1p<A>(a0, a1, a2); };
  static_assert(available_sha_1<native::isa{native::arm_feature::sha1}, uint32x4_t, std::uint32_t, uint32x4_t>);
  static_assert(!available_sha_1<native::scalar, uint32x4_t, std::uint32_t, uint32x4_t>);
  static_assert(!available_sha_1<native::isa{native::arm_feature::sha1}, float64x2_t, std::uint32_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_2 = requires(T0 a0, T1 a1, T2 a2) { native::sha1m<A>(a0, a1, a2); };
  static_assert(available_sha_2<native::isa{native::arm_feature::sha1}, uint32x4_t, std::uint32_t, uint32x4_t>);
  static_assert(!available_sha_2<native::scalar, uint32x4_t, std::uint32_t, uint32x4_t>);
  static_assert(!available_sha_2<native::isa{native::arm_feature::sha1}, float64x2_t, std::uint32_t, uint32x4_t>);
  template<native::isa A, class T0> concept available_sha_3 = requires(T0 a0) { native::sha1h<A>(a0); };
  static_assert(available_sha_3<native::isa{native::arm_feature::sha1}, std::uint32_t>);
  static_assert(!available_sha_3<native::scalar, std::uint32_t>);
  static_assert(!available_sha_3<native::isa{native::arm_feature::sha1}, float64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_4 = requires(T0 a0, T1 a1, T2 a2) { native::sha1su0<A>(a0, a1, a2); };
  static_assert(available_sha_4<native::isa{native::arm_feature::sha1}, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_4<native::scalar, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_4<native::isa{native::arm_feature::sha1}, float64x2_t, uint32x4_t, uint32x4_t>);
  template<native::isa A, class T0, class T1> concept available_sha_5 = requires(T0 a0, T1 a1) { native::sha1su1<A>(a0, a1); };
  static_assert(available_sha_5<native::isa{native::arm_feature::sha1}, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_5<native::scalar, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_5<native::isa{native::arm_feature::sha1}, float64x2_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_6 = requires(T0 a0, T1 a1, T2 a2) { native::sha256h<A>(a0, a1, a2); };
  static_assert(available_sha_6<native::isa{native::arm_feature::sha2}, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_6<native::scalar, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_6<native::isa{native::arm_feature::sha2}, float64x2_t, uint32x4_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_7 = requires(T0 a0, T1 a1, T2 a2) { native::sha256h2<A>(a0, a1, a2); };
  static_assert(available_sha_7<native::isa{native::arm_feature::sha2}, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_7<native::scalar, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_7<native::isa{native::arm_feature::sha2}, float64x2_t, uint32x4_t, uint32x4_t>);
  template<native::isa A, class T0, class T1> concept available_sha_8 = requires(T0 a0, T1 a1) { native::sha256su0<A>(a0, a1); };
  static_assert(available_sha_8<native::isa{native::arm_feature::sha2}, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_8<native::scalar, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_8<native::isa{native::arm_feature::sha2}, float64x2_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_9 = requires(T0 a0, T1 a1, T2 a2) { native::sha256su1<A>(a0, a1, a2); };
  static_assert(available_sha_9<native::isa{native::arm_feature::sha2}, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_9<native::scalar, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_9<native::isa{native::arm_feature::sha2}, float64x2_t, uint32x4_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_10 = requires(T0 a0, T1 a1, T2 a2) { native::sha512h<A>(a0, a1, a2); };
  static_assert(available_sha_10<native::isa{native::arm_feature::sha512}, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_10<native::scalar, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_10<native::isa{native::arm_feature::sha512}, float64x2_t, uint64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_11 = requires(T0 a0, T1 a1, T2 a2) { native::sha512h2<A>(a0, a1, a2); };
  static_assert(available_sha_11<native::isa{native::arm_feature::sha512}, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_11<native::scalar, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_11<native::isa{native::arm_feature::sha512}, float64x2_t, uint64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1> concept available_sha_12 = requires(T0 a0, T1 a1) { native::sha512su0<A>(a0, a1); };
  static_assert(available_sha_12<native::isa{native::arm_feature::sha512}, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_12<native::scalar, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_12<native::isa{native::arm_feature::sha512}, float64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_13 = requires(T0 a0, T1 a1, T2 a2) { native::sha512su1<A>(a0, a1, a2); };
  static_assert(available_sha_13<native::isa{native::arm_feature::sha512}, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_13<native::scalar, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_13<native::isa{native::arm_feature::sha512}, float64x2_t, uint64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_14 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_14<native::isa{native::arm_feature::sha3}, uint8x16_t, uint8x16_t, uint8x16_t>);
  static_assert(!available_sha_14<native::scalar, uint8x16_t, uint8x16_t, uint8x16_t>);
  static_assert(!available_sha_14<native::isa{native::arm_feature::sha3}, float64x2_t, uint8x16_t, uint8x16_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_15 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_15<native::isa{native::arm_feature::sha3}, uint16x8_t, uint16x8_t, uint16x8_t>);
  static_assert(!available_sha_15<native::scalar, uint16x8_t, uint16x8_t, uint16x8_t>);
  static_assert(!available_sha_15<native::isa{native::arm_feature::sha3}, float64x2_t, uint16x8_t, uint16x8_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_16 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_16<native::isa{native::arm_feature::sha3}, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_16<native::scalar, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_16<native::isa{native::arm_feature::sha3}, float64x2_t, uint32x4_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_17 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_17<native::isa{native::arm_feature::sha3}, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_17<native::scalar, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_17<native::isa{native::arm_feature::sha3}, float64x2_t, uint64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_18 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_18<native::isa{native::arm_feature::sha3}, int8x16_t, int8x16_t, int8x16_t>);
  static_assert(!available_sha_18<native::scalar, int8x16_t, int8x16_t, int8x16_t>);
  static_assert(!available_sha_18<native::isa{native::arm_feature::sha3}, float64x2_t, int8x16_t, int8x16_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_19 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_19<native::isa{native::arm_feature::sha3}, int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!available_sha_19<native::scalar, int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!available_sha_19<native::isa{native::arm_feature::sha3}, float64x2_t, int16x8_t, int16x8_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_20 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_20<native::isa{native::arm_feature::sha3}, int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!available_sha_20<native::scalar, int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!available_sha_20<native::isa{native::arm_feature::sha3}, float64x2_t, int32x4_t, int32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_21 = requires(T0 a0, T1 a1, T2 a2) { native::eor3<A>(a0, a1, a2); };
  static_assert(available_sha_21<native::isa{native::arm_feature::sha3}, int64x2_t, int64x2_t, int64x2_t>);
  static_assert(!available_sha_21<native::scalar, int64x2_t, int64x2_t, int64x2_t>);
  static_assert(!available_sha_21<native::isa{native::arm_feature::sha3}, float64x2_t, int64x2_t, int64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_22 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_22<native::isa{native::arm_feature::sha3}, uint8x16_t, uint8x16_t, uint8x16_t>);
  static_assert(!available_sha_22<native::scalar, uint8x16_t, uint8x16_t, uint8x16_t>);
  static_assert(!available_sha_22<native::isa{native::arm_feature::sha3}, float64x2_t, uint8x16_t, uint8x16_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_23 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_23<native::isa{native::arm_feature::sha3}, uint16x8_t, uint16x8_t, uint16x8_t>);
  static_assert(!available_sha_23<native::scalar, uint16x8_t, uint16x8_t, uint16x8_t>);
  static_assert(!available_sha_23<native::isa{native::arm_feature::sha3}, float64x2_t, uint16x8_t, uint16x8_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_24 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_24<native::isa{native::arm_feature::sha3}, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_24<native::scalar, uint32x4_t, uint32x4_t, uint32x4_t>);
  static_assert(!available_sha_24<native::isa{native::arm_feature::sha3}, float64x2_t, uint32x4_t, uint32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_25 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_25<native::isa{native::arm_feature::sha3}, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_25<native::scalar, uint64x2_t, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_25<native::isa{native::arm_feature::sha3}, float64x2_t, uint64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_26 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_26<native::isa{native::arm_feature::sha3}, int8x16_t, int8x16_t, int8x16_t>);
  static_assert(!available_sha_26<native::scalar, int8x16_t, int8x16_t, int8x16_t>);
  static_assert(!available_sha_26<native::isa{native::arm_feature::sha3}, float64x2_t, int8x16_t, int8x16_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_27 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_27<native::isa{native::arm_feature::sha3}, int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!available_sha_27<native::scalar, int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!available_sha_27<native::isa{native::arm_feature::sha3}, float64x2_t, int16x8_t, int16x8_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_28 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_28<native::isa{native::arm_feature::sha3}, int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!available_sha_28<native::scalar, int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!available_sha_28<native::isa{native::arm_feature::sha3}, float64x2_t, int32x4_t, int32x4_t>);
  template<native::isa A, class T0, class T1, class T2> concept available_sha_29 = requires(T0 a0, T1 a1, T2 a2) { native::bcax<A>(a0, a1, a2); };
  static_assert(available_sha_29<native::isa{native::arm_feature::sha3}, int64x2_t, int64x2_t, int64x2_t>);
  static_assert(!available_sha_29<native::scalar, int64x2_t, int64x2_t, int64x2_t>);
  static_assert(!available_sha_29<native::isa{native::arm_feature::sha3}, float64x2_t, int64x2_t, int64x2_t>);
  template<native::isa A, class T0, class T1> concept available_sha_30 = requires(T0 a0, T1 a1) { native::rax1<A>(a0, a1); };
  static_assert(available_sha_30<native::isa{native::arm_feature::sha3}, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_30<native::scalar, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_30<native::isa{native::arm_feature::sha3}, float64x2_t, uint64x2_t>);
  template<native::isa A, class T0, class T1> concept available_sha_31 = requires(T0 a0, T1 a1) { native::xar<A, 0>(a0, a1); };
  static_assert(available_sha_31<native::isa{native::arm_feature::sha3}, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_31<native::scalar, uint64x2_t, uint64x2_t>);
  static_assert(!available_sha_31<native::isa{native::arm_feature::sha3}, float64x2_t, uint64x2_t>);
}
