// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
#include <concepts>
#include <utility>
namespace fcma_simd_contract {
  constexpr auto arch_0 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_0 = requires(A... a) { native::fcadd<arch_0, 90>(a...); };
  static_assert(accepts_0<native::simd<float, 2, arch_0>, native::simd<float, 2, arch_0>>);
  static_assert(!accepts_0<native::simd<std::uint32_t, 2, arch_0>, native::simd<float, 2, arch_0>>);
  static_assert(std::same_as<decltype(native::fcadd<arch_0, 90>(std::declval<native::simd<float, 2, arch_0>>(), std::declval<native::simd<float, 2, arch_0>>())), native::simd<float, 2, arch_0>>);
  static_assert(!accepts_0<float32x2_t, float32x2_t>);
  static_assert(!accepts_0<native::simd<float, 2, (arch_0 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 2, arch_0>>);
  constexpr auto arch_1 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_1 = requires(A... a) { native::fcmla<arch_1, 90>(a...); };
  static_assert(accepts_1<native::simd<float, 2, arch_1>, native::simd<float, 2, arch_1>, native::simd<float, 2, arch_1>>);
  static_assert(!accepts_1<native::simd<std::uint32_t, 2, arch_1>, native::simd<float, 2, arch_1>, native::simd<float, 2, arch_1>>);
  static_assert(std::same_as<decltype(native::fcmla<arch_1, 90>(std::declval<native::simd<float, 2, arch_1>>(), std::declval<native::simd<float, 2, arch_1>>(), std::declval<native::simd<float, 2, arch_1>>())), native::simd<float, 2, arch_1>>);
  static_assert(!accepts_1<float32x2_t, float32x2_t, float32x2_t>);
  static_assert(!accepts_1<native::simd<float, 2, (arch_1 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 2, arch_1>, native::simd<float, 2, arch_1>>);
  constexpr auto arch_2 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_2 = requires(A... a) { native::fcmla_lane<arch_2, 90, 0>(a...); };
  static_assert(accepts_2<native::simd<float, 2, arch_2>, native::simd<float, 2, arch_2>, native::simd<float, 2, arch_2>>);
  static_assert(!accepts_2<native::simd<std::uint32_t, 2, arch_2>, native::simd<float, 2, arch_2>, native::simd<float, 2, arch_2>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_2, 90, 0>(std::declval<native::simd<float, 2, arch_2>>(), std::declval<native::simd<float, 2, arch_2>>(), std::declval<native::simd<float, 2, arch_2>>())), native::simd<float, 2, arch_2>>);
  static_assert(!accepts_2<float32x2_t, float32x2_t, float32x2_t>);
  static_assert(!accepts_2<native::simd<float, 2, (arch_2 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 2, arch_2>, native::simd<float, 2, arch_2>>);
  constexpr auto arch_3 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_3 = requires(A... a) { native::fcmla_lane<arch_3, 90, 0>(a...); };
  static_assert(accepts_3<native::simd<float, 2, arch_3>, native::simd<float, 2, arch_3>, native::simd<float, 4, arch_3>>);
  static_assert(!accepts_3<native::simd<std::uint32_t, 2, arch_3>, native::simd<float, 2, arch_3>, native::simd<float, 4, arch_3>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_3, 90, 0>(std::declval<native::simd<float, 2, arch_3>>(), std::declval<native::simd<float, 2, arch_3>>(), std::declval<native::simd<float, 4, arch_3>>())), native::simd<float, 2, arch_3>>);
  static_assert(!accepts_3<float32x2_t, float32x2_t, float32x4_t>);
  static_assert(!accepts_3<native::simd<float, 2, (arch_3 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 2, arch_3>, native::simd<float, 4, arch_3>>);
  constexpr auto arch_4 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_4 = requires(A... a) { native::fcadd<arch_4, 90>(a...); };
  static_assert(accepts_4<native::simd<float, 4, arch_4>, native::simd<float, 4, arch_4>>);
  static_assert(!accepts_4<native::simd<std::uint32_t, 4, arch_4>, native::simd<float, 4, arch_4>>);
  static_assert(std::same_as<decltype(native::fcadd<arch_4, 90>(std::declval<native::simd<float, 4, arch_4>>(), std::declval<native::simd<float, 4, arch_4>>())), native::simd<float, 4, arch_4>>);
  static_assert(!accepts_4<float32x4_t, float32x4_t>);
  static_assert(!accepts_4<native::simd<float, 4, (arch_4 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 4, arch_4>>);
  constexpr auto arch_5 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_5 = requires(A... a) { native::fcmla<arch_5, 90>(a...); };
  static_assert(accepts_5<native::simd<float, 4, arch_5>, native::simd<float, 4, arch_5>, native::simd<float, 4, arch_5>>);
  static_assert(!accepts_5<native::simd<std::uint32_t, 4, arch_5>, native::simd<float, 4, arch_5>, native::simd<float, 4, arch_5>>);
  static_assert(std::same_as<decltype(native::fcmla<arch_5, 90>(std::declval<native::simd<float, 4, arch_5>>(), std::declval<native::simd<float, 4, arch_5>>(), std::declval<native::simd<float, 4, arch_5>>())), native::simd<float, 4, arch_5>>);
  static_assert(!accepts_5<float32x4_t, float32x4_t, float32x4_t>);
  static_assert(!accepts_5<native::simd<float, 4, (arch_5 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 4, arch_5>, native::simd<float, 4, arch_5>>);
  constexpr auto arch_6 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_6 = requires(A... a) { native::fcmla_lane<arch_6, 90, 0>(a...); };
  static_assert(accepts_6<native::simd<float, 4, arch_6>, native::simd<float, 4, arch_6>, native::simd<float, 2, arch_6>>);
  static_assert(!accepts_6<native::simd<std::uint32_t, 4, arch_6>, native::simd<float, 4, arch_6>, native::simd<float, 2, arch_6>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_6, 90, 0>(std::declval<native::simd<float, 4, arch_6>>(), std::declval<native::simd<float, 4, arch_6>>(), std::declval<native::simd<float, 2, arch_6>>())), native::simd<float, 4, arch_6>>);
  static_assert(!accepts_6<float32x4_t, float32x4_t, float32x2_t>);
  static_assert(!accepts_6<native::simd<float, 4, (arch_6 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 4, arch_6>, native::simd<float, 2, arch_6>>);
  constexpr auto arch_7 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_7 = requires(A... a) { native::fcmla_lane<arch_7, 90, 0>(a...); };
  static_assert(accepts_7<native::simd<float, 4, arch_7>, native::simd<float, 4, arch_7>, native::simd<float, 4, arch_7>>);
  static_assert(!accepts_7<native::simd<std::uint32_t, 4, arch_7>, native::simd<float, 4, arch_7>, native::simd<float, 4, arch_7>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_7, 90, 0>(std::declval<native::simd<float, 4, arch_7>>(), std::declval<native::simd<float, 4, arch_7>>(), std::declval<native::simd<float, 4, arch_7>>())), native::simd<float, 4, arch_7>>);
  static_assert(!accepts_7<float32x4_t, float32x4_t, float32x4_t>);
  static_assert(!accepts_7<native::simd<float, 4, (arch_7 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<float, 4, arch_7>, native::simd<float, 4, arch_7>>);
  constexpr auto arch_8 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_8 = requires(A... a) { native::fcadd<arch_8, 90>(a...); };
  static_assert(accepts_8<native::simd<double, 2, arch_8>, native::simd<double, 2, arch_8>>);
  static_assert(!accepts_8<native::simd<std::uint64_t, 2, arch_8>, native::simd<double, 2, arch_8>>);
  static_assert(std::same_as<decltype(native::fcadd<arch_8, 90>(std::declval<native::simd<double, 2, arch_8>>(), std::declval<native::simd<double, 2, arch_8>>())), native::simd<double, 2, arch_8>>);
  static_assert(!accepts_8<float64x2_t, float64x2_t>);
  static_assert(!accepts_8<native::simd<double, 2, (arch_8 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<double, 2, arch_8>>);
  constexpr auto arch_9 = native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum));
  template<class... A> concept accepts_9 = requires(A... a) { native::fcmla<arch_9, 90>(a...); };
  static_assert(accepts_9<native::simd<double, 2, arch_9>, native::simd<double, 2, arch_9>, native::simd<double, 2, arch_9>>);
  static_assert(!accepts_9<native::simd<std::uint64_t, 2, arch_9>, native::simd<double, 2, arch_9>, native::simd<double, 2, arch_9>>);
  static_assert(std::same_as<decltype(native::fcmla<arch_9, 90>(std::declval<native::simd<double, 2, arch_9>>(), std::declval<native::simd<double, 2, arch_9>>(), std::declval<native::simd<double, 2, arch_9>>())), native::simd<double, 2, arch_9>>);
  static_assert(!accepts_9<float64x2_t, float64x2_t, float64x2_t>);
  static_assert(!accepts_9<native::simd<double, 2, (arch_9 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<double, 2, arch_9>, native::simd<double, 2, arch_9>>);
  constexpr auto arch_10 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_10 = requires(A... a) { native::fcadd<arch_10, 90>(a...); };
  static_assert(accepts_10<native::simd<native::fp16, 4, arch_10>, native::simd<native::fp16, 4, arch_10>>);
  static_assert(!accepts_10<native::simd<std::uint16_t, 4, arch_10>, native::simd<native::fp16, 4, arch_10>>);
  static_assert(std::same_as<decltype(native::fcadd<arch_10, 90>(std::declval<native::simd<native::fp16, 4, arch_10>>(), std::declval<native::simd<native::fp16, 4, arch_10>>())), native::simd<native::fp16, 4, arch_10>>);
  static_assert(!accepts_10<float16x4_t, float16x4_t>);
  static_assert(!accepts_10<native::simd<native::fp16, 4, (arch_10 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 4, arch_10>>);
  constexpr auto arch_11 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_11 = requires(A... a) { native::fcmla<arch_11, 90>(a...); };
  static_assert(accepts_11<native::simd<native::fp16, 4, arch_11>, native::simd<native::fp16, 4, arch_11>, native::simd<native::fp16, 4, arch_11>>);
  static_assert(!accepts_11<native::simd<std::uint16_t, 4, arch_11>, native::simd<native::fp16, 4, arch_11>, native::simd<native::fp16, 4, arch_11>>);
  static_assert(std::same_as<decltype(native::fcmla<arch_11, 90>(std::declval<native::simd<native::fp16, 4, arch_11>>(), std::declval<native::simd<native::fp16, 4, arch_11>>(), std::declval<native::simd<native::fp16, 4, arch_11>>())), native::simd<native::fp16, 4, arch_11>>);
  static_assert(!accepts_11<float16x4_t, float16x4_t, float16x4_t>);
  static_assert(!accepts_11<native::simd<native::fp16, 4, (arch_11 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 4, arch_11>, native::simd<native::fp16, 4, arch_11>>);
  constexpr auto arch_12 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_12 = requires(A... a) { native::fcmla_lane<arch_12, 90, 0>(a...); };
  static_assert(accepts_12<native::simd<native::fp16, 4, arch_12>, native::simd<native::fp16, 4, arch_12>, native::simd<native::fp16, 4, arch_12>>);
  static_assert(!accepts_12<native::simd<std::uint16_t, 4, arch_12>, native::simd<native::fp16, 4, arch_12>, native::simd<native::fp16, 4, arch_12>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_12, 90, 0>(std::declval<native::simd<native::fp16, 4, arch_12>>(), std::declval<native::simd<native::fp16, 4, arch_12>>(), std::declval<native::simd<native::fp16, 4, arch_12>>())), native::simd<native::fp16, 4, arch_12>>);
  static_assert(!accepts_12<float16x4_t, float16x4_t, float16x4_t>);
  static_assert(!accepts_12<native::simd<native::fp16, 4, (arch_12 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 4, arch_12>, native::simd<native::fp16, 4, arch_12>>);
  constexpr auto arch_13 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_13 = requires(A... a) { native::fcmla_lane<arch_13, 90, 0>(a...); };
  static_assert(accepts_13<native::simd<native::fp16, 4, arch_13>, native::simd<native::fp16, 4, arch_13>, native::simd<native::fp16, 8, arch_13>>);
  static_assert(!accepts_13<native::simd<std::uint16_t, 4, arch_13>, native::simd<native::fp16, 4, arch_13>, native::simd<native::fp16, 8, arch_13>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_13, 90, 0>(std::declval<native::simd<native::fp16, 4, arch_13>>(), std::declval<native::simd<native::fp16, 4, arch_13>>(), std::declval<native::simd<native::fp16, 8, arch_13>>())), native::simd<native::fp16, 4, arch_13>>);
  static_assert(!accepts_13<float16x4_t, float16x4_t, float16x8_t>);
  static_assert(!accepts_13<native::simd<native::fp16, 4, (arch_13 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 4, arch_13>, native::simd<native::fp16, 8, arch_13>>);
  constexpr auto arch_14 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_14 = requires(A... a) { native::fcadd<arch_14, 90>(a...); };
  static_assert(accepts_14<native::simd<native::fp16, 8, arch_14>, native::simd<native::fp16, 8, arch_14>>);
  static_assert(!accepts_14<native::simd<std::uint16_t, 8, arch_14>, native::simd<native::fp16, 8, arch_14>>);
  static_assert(std::same_as<decltype(native::fcadd<arch_14, 90>(std::declval<native::simd<native::fp16, 8, arch_14>>(), std::declval<native::simd<native::fp16, 8, arch_14>>())), native::simd<native::fp16, 8, arch_14>>);
  static_assert(!accepts_14<float16x8_t, float16x8_t>);
  static_assert(!accepts_14<native::simd<native::fp16, 8, (arch_14 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 8, arch_14>>);
  constexpr auto arch_15 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_15 = requires(A... a) { native::fcmla<arch_15, 90>(a...); };
  static_assert(accepts_15<native::simd<native::fp16, 8, arch_15>, native::simd<native::fp16, 8, arch_15>, native::simd<native::fp16, 8, arch_15>>);
  static_assert(!accepts_15<native::simd<std::uint16_t, 8, arch_15>, native::simd<native::fp16, 8, arch_15>, native::simd<native::fp16, 8, arch_15>>);
  static_assert(std::same_as<decltype(native::fcmla<arch_15, 90>(std::declval<native::simd<native::fp16, 8, arch_15>>(), std::declval<native::simd<native::fp16, 8, arch_15>>(), std::declval<native::simd<native::fp16, 8, arch_15>>())), native::simd<native::fp16, 8, arch_15>>);
  static_assert(!accepts_15<float16x8_t, float16x8_t, float16x8_t>);
  static_assert(!accepts_15<native::simd<native::fp16, 8, (arch_15 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 8, arch_15>, native::simd<native::fp16, 8, arch_15>>);
  constexpr auto arch_16 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_16 = requires(A... a) { native::fcmla_lane<arch_16, 90, 0>(a...); };
  static_assert(accepts_16<native::simd<native::fp16, 8, arch_16>, native::simd<native::fp16, 8, arch_16>, native::simd<native::fp16, 4, arch_16>>);
  static_assert(!accepts_16<native::simd<std::uint16_t, 8, arch_16>, native::simd<native::fp16, 8, arch_16>, native::simd<native::fp16, 4, arch_16>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_16, 90, 0>(std::declval<native::simd<native::fp16, 8, arch_16>>(), std::declval<native::simd<native::fp16, 8, arch_16>>(), std::declval<native::simd<native::fp16, 4, arch_16>>())), native::simd<native::fp16, 8, arch_16>>);
  static_assert(!accepts_16<float16x8_t, float16x8_t, float16x4_t>);
  static_assert(!accepts_16<native::simd<native::fp16, 8, (arch_16 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 8, arch_16>, native::simd<native::fp16, 4, arch_16>>);
  constexpr auto arch_17 = (native::feature_closure(native::isa<native::arm>(native::arm_feature::complxnum)) & native::neon_fp16);
  template<class... A> concept accepts_17 = requires(A... a) { native::fcmla_lane<arch_17, 90, 0>(a...); };
  static_assert(accepts_17<native::simd<native::fp16, 8, arch_17>, native::simd<native::fp16, 8, arch_17>, native::simd<native::fp16, 8, arch_17>>);
  static_assert(!accepts_17<native::simd<std::uint16_t, 8, arch_17>, native::simd<native::fp16, 8, arch_17>, native::simd<native::fp16, 8, arch_17>>);
  static_assert(std::same_as<decltype(native::fcmla_lane<arch_17, 90, 0>(std::declval<native::simd<native::fp16, 8, arch_17>>(), std::declval<native::simd<native::fp16, 8, arch_17>>(), std::declval<native::simd<native::fp16, 8, arch_17>>())), native::simd<native::fp16, 8, arch_17>>);
  static_assert(!accepts_17<float16x8_t, float16x8_t, float16x8_t>);
  static_assert(!accepts_17<native::simd<native::fp16, 8, (arch_17 & native::isa<native::arm>(native::arm_feature::crc))>, native::simd<native::fp16, 8, arch_17>, native::simd<native::fp16, 8, arch_17>>);
}
