#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
"""Generate independent OpenSSL/hashlib digests for one-block instruction tests."""
import hashlib
from pathlib import Path


def words(data, width):
    return [int.from_bytes(data[i:i + width], 'big') for i in range(0, len(data), width)]


def array(name, values, bits):
    rows = [', '.join(f'0x{x:0{bits // 4}x}' for x in values[i:i + 4])
            for i in range(0, len(values), 4)]
    return (f'inline constexpr std::array<std::uint{bits}_t,{len(values)}> {name}{{\n  '
            + ',\n  '.join(rows) + '};\n')


out = '''// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
// Independent Python hashlib/OpenSSL digests; generated by generate_seeded.py.
'''
for algorithm, sizes, width, blocksize, tail, features in [
    ('sha512', [0, 1, 31, 63, 111], 8, 128, 16, ['sha512', 'avx2']),
    ('sm3', [0, 1, 15, 31, 55], 4, 64, 8, ['sm3', 'sse2']),
]:
    for i, length in enumerate(sizes):
        state = 0x6d2b79f5
        message = bytearray()
        for _ in range(length):
            state ^= (state << 13) & 0xffffffff
            state ^= state >> 17
            state ^= (state << 5) & 0xffffffff
            message.append(state & 255)
        padded = message + b'\x80' + bytes(blocksize - tail - 1 - length) + (length * 8).to_bytes(tail, 'big')
        digest = hashlib.new(algorithm, message).digest()
        block = f'{algorithm}_block_{i}'
        expected = f'{algorithm}_expected_{i}'
        out += array(block, words(padded, width), width * 8)
        out += array(expected, words(digest, width), width * 8)
        for feature in features:
            out += (f'static_assert(checks::{algorithm}_block<native::target_features<native::x86>("{feature}")>'
                    f'({block},{expected}));\n')
Path(__file__).with_name('seeded.h').write_text(out)
