// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
// Independent Python hashlib/OpenSSL digests; generated by generate_seeded.py.
inline constexpr std::array<std::uint64_t,16> sha512_block_0{
  0x8000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000};
inline constexpr std::array<std::uint64_t,8> sha512_expected_0{
  0xcf83e1357eefb8bd, 0xf1542850d66d8007, 0xd620e4050b5715dc, 0x83f4a921d36ce9ce,
  0x47d0d13c5d85f2b0, 0xff8318d2877eec2f, 0x63b931bd47417a81, 0xa538327af927da3e};
static_assert(checks::sha512_block<native::target_features<native::x86>("sha512")>(sha512_block_0,sha512_expected_0));
static_assert(checks::sha512_block<native::target_features<native::x86>("avx2")>(sha512_block_0,sha512_expected_0));
inline constexpr std::array<std::uint64_t,16> sha512_block_1{
  0x1f80000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000008};
inline constexpr std::array<std::uint64_t,8> sha512_expected_1{
  0x4ff3abc9000066dd, 0x768a53dd1e3d69bf, 0x85cccbda132087f0, 0x867e910f40305500,
  0xf6a2b39739f801d5, 0x195b0a7de79da71e, 0x086277ebe9540c5b, 0x234b594b1deedede};
static_assert(checks::sha512_block<native::target_features<native::x86>("sha512")>(sha512_block_1,sha512_expected_1));
static_assert(checks::sha512_block<native::target_features<native::x86>("avx2")>(sha512_block_1,sha512_expected_1));
inline constexpr std::array<std::uint64_t,16> sha512_block_2{
  0x1f19289dcce78c17, 0x42ceefbe0a1fa96a, 0xfcc607fcbb72b24f, 0xf97da983c1193480,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00000000000000f8};
inline constexpr std::array<std::uint64_t,8> sha512_expected_2{
  0xec5866bd71f28843, 0x6f558d1ca725be3b, 0x6e74cb540d8dad9d, 0xf84e394489997383,
  0x31852dfe696353b8, 0x422b1161c7be2b39, 0xb7cfb388bcf9f822, 0xe3e50557358a5b33};
static_assert(checks::sha512_block<native::target_features<native::x86>("sha512")>(sha512_block_2,sha512_expected_2));
static_assert(checks::sha512_block<native::target_features<native::x86>("avx2")>(sha512_block_2,sha512_expected_2));
inline constexpr std::array<std::uint64_t,16> sha512_block_3{
  0x1f19289dcce78c17, 0x42ceefbe0a1fa96a, 0xfcc607fcbb72b24f, 0xf97da983c119349c,
  0x6af72655cc67c45b, 0x5fd3980d7900f7ee, 0xb4ca81fa0cd706ff, 0x9ad87727721a3180,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
  0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00000000000001f8};
inline constexpr std::array<std::uint64_t,8> sha512_expected_3{
  0xac70d554a43a9ab0, 0xc03d742c310353c1, 0x8719b17d13083ade, 0x0efc82afaca3681c,
  0x40758c559f1cf90c, 0x60825e7c7eb1abbd, 0x8618a174b1b98c2c, 0x24c00aa93672af42};
static_assert(checks::sha512_block<native::target_features<native::x86>("sha512")>(sha512_block_3,sha512_expected_3));
static_assert(checks::sha512_block<native::target_features<native::x86>("avx2")>(sha512_block_3,sha512_expected_3));
inline constexpr std::array<std::uint64_t,16> sha512_block_4{
  0x1f19289dcce78c17, 0x42ceefbe0a1fa96a, 0xfcc607fcbb72b24f, 0xf97da983c119349c,
  0x6af72655cc67c45b, 0x5fd3980d7900f7ee, 0xb4ca81fa0cd706ff, 0x9ad87727721a315a,
  0x0ec8d20c43a7655e, 0x7bd0b069c8d62ed3, 0xf34929ee88aee693, 0x4f9c54dc4fbc9c8b,
  0xee01c768ea749027, 0x8e11466a83720d80, 0x0000000000000000, 0x0000000000000378};
inline constexpr std::array<std::uint64_t,8> sha512_expected_4{
  0x3cc2b1c13450c2ee, 0xf24c8b69d9b0894b, 0x229056e893f63ef3, 0x5125426749a03006,
  0x8f73fb268e17f5a2, 0xd40e52a66d93de31, 0xd679ffc0ef31d6cc, 0x9c0d45d2254dd665};
static_assert(checks::sha512_block<native::target_features<native::x86>("sha512")>(sha512_block_4,sha512_expected_4));
static_assert(checks::sha512_block<native::target_features<native::x86>("avx2")>(sha512_block_4,sha512_expected_4));
inline constexpr std::array<std::uint32_t,16> sm3_block_0{
  0x80000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000000};
inline constexpr std::array<std::uint32_t,8> sm3_expected_0{
  0x1ab21d83, 0x55cfa17f, 0x8e611948, 0x31e81a8f,
  0x22bec8c7, 0x28fefb74, 0x7ed035eb, 0x5082aa2b};
static_assert(checks::sm3_block<native::target_features<native::x86>("sm3")>(sm3_block_0,sm3_expected_0));
static_assert(checks::sm3_block<native::target_features<native::x86>("sse2")>(sm3_block_0,sm3_expected_0));
inline constexpr std::array<std::uint32_t,16> sm3_block_1{
  0x1f800000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000008};
inline constexpr std::array<std::uint32_t,8> sm3_expected_1{
  0x5d3ff8aa, 0x6f039042, 0x33d3ad14, 0x7f71688d,
  0x28086506, 0x28cde76c, 0x5d3603a5, 0xf851961e};
static_assert(checks::sm3_block<native::target_features<native::x86>("sm3")>(sm3_block_1,sm3_expected_1));
static_assert(checks::sm3_block<native::target_features<native::x86>("sse2")>(sm3_block_1,sm3_expected_1));
inline constexpr std::array<std::uint32_t,16> sm3_block_2{
  0x1f19289d, 0xcce78c17, 0x42ceefbe, 0x0a1fa980,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x00000078};
inline constexpr std::array<std::uint32_t,8> sm3_expected_2{
  0x6cd171b4, 0x4e48f89d, 0xc85465ff, 0xcf5b0bb3,
  0xca1a7e7b, 0xc7384318, 0x5647f33a, 0x3f065b0d};
static_assert(checks::sm3_block<native::target_features<native::x86>("sm3")>(sm3_block_2,sm3_expected_2));
static_assert(checks::sm3_block<native::target_features<native::x86>("sse2")>(sm3_block_2,sm3_expected_2));
inline constexpr std::array<std::uint32_t,16> sm3_block_3{
  0x1f19289d, 0xcce78c17, 0x42ceefbe, 0x0a1fa96a,
  0xfcc607fc, 0xbb72b24f, 0xf97da983, 0xc1193480,
  0x00000000, 0x00000000, 0x00000000, 0x00000000,
  0x00000000, 0x00000000, 0x00000000, 0x000000f8};
inline constexpr std::array<std::uint32_t,8> sm3_expected_3{
  0x0159aa7c, 0x0df6cf22, 0x839cba3c, 0x778d1673,
  0x00024b29, 0x88247b18, 0xb9e25aea, 0xbfd51566};
static_assert(checks::sm3_block<native::target_features<native::x86>("sm3")>(sm3_block_3,sm3_expected_3));
static_assert(checks::sm3_block<native::target_features<native::x86>("sse2")>(sm3_block_3,sm3_expected_3));
inline constexpr std::array<std::uint32_t,16> sm3_block_4{
  0x1f19289d, 0xcce78c17, 0x42ceefbe, 0x0a1fa96a,
  0xfcc607fc, 0xbb72b24f, 0xf97da983, 0xc119349c,
  0x6af72655, 0xcc67c45b, 0x5fd3980d, 0x7900f7ee,
  0xb4ca81fa, 0x0cd70680, 0x00000000, 0x000001b8};
inline constexpr std::array<std::uint32_t,8> sm3_expected_4{
  0xce6c6b9c, 0x46befa92, 0xc336c5d9, 0xf5b02f5e,
  0x1a541a82, 0x352d923d, 0xa7e86762, 0x09183b62};
static_assert(checks::sm3_block<native::target_features<native::x86>("sm3")>(sm3_block_4,sm3_expected_4));
static_assert(checks::sm3_block<native::target_features<native::x86>("sse2")>(sm3_block_4,sm3_expected_4));
