# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0

# Select the ISA of one producer/consumer target. Never propagate it to callers.
# Linking simd::simd alone does not select an ISA or a runtime dispatch policy.
function(simd_target_profile target profile)
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "simd_target_profile requires an existing target: ${target}")
  endif()
  string(TOUPPER "${profile}" profile)
  if(NOT profile MATCHES "^(AVX2|AVX512|NEON)$")
    message(FATAL_ERROR "Unknown simd target profile: ${profile}")
  endif()
  if(profile STREQUAL "NEON")
    if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
      message(FATAL_ERROR "The NEON profile requires an arm64 target toolchain.")
    endif()
  elseif(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|amd64|x86_64|X86_64)$")
    message(FATAL_ERROR "The ${profile} profile requires an x86-64 target toolchain.")
  endif()
  get_target_property(previous "${target}" SIMD_TARGET_PROFILE)
  if(previous AND NOT previous STREQUAL profile)
    message(FATAL_ERROR "Target ${target} already selects ${previous}, not ${profile}.")
  endif()
  if(previous)
    return()
  endif()
  set_property(TARGET "${target}" PROPERTY SIMD_TARGET_PROFILE "${profile}")
  set(flags)
  if(NOT profile STREQUAL "NEON")
    list(APPEND flags -mavx2 -mfma -mbmi2)
  endif()
  if(profile STREQUAL "AVX512")
    list(APPEND flags -mavx512f -mavx512dq -mavx512bw -mavx512vl)
  endif()
  if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      message(FATAL_ERROR "The Windows simd profiles require clang-cl.")
    endif()
    foreach(flag IN LISTS flags)
      target_compile_options("${target}" PRIVATE "/clang:${flag}")
    endforeach()
  else()
    target_compile_options("${target}" PRIVATE ${flags})
  endif()
endfunction()
