# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
cmake_minimum_required(VERSION 4.4)
# Inspect only providers still present in the current single-config Ninja graph.
if(NOT DEFINED NINJA_FILE)
  set(NINJA_FILE "${BUILD_DIR}/build.ninja")
endif()
cmake_path(ABSOLUTE_PATH NINJA_FILE NORMALIZE)
cmake_path(GET NINJA_FILE PARENT_PATH ninja_dir)
file(STRINGS "${NINJA_FILE}" ninja_edges REGEX "^build .*CXX[.]dd ")
set(active_maps)
foreach(edge IN LISTS ninja_edges)
  string(REPLACE "\\" "/" edge "${edge}")
  if(edge MATCHES "^build (.+/CXX[.]dd) [|:]")
    set(dd "${CMAKE_MATCH_1}")
    # CMake's Ninja output escapes spaces, drive colons, and literal dollars.
    string(REPLACE "$ " " " dd "${dd}")
    string(REPLACE "$:" ":" dd "${dd}")
    string(REPLACE "$$" "$" dd "${dd}")
    cmake_path(ABSOLUTE_PATH dd BASE_DIRECTORY "${ninja_dir}" NORMALIZE)
    cmake_path(GET dd PARENT_PATH provider_dir)
    list(APPEND active_maps "${provider_dir}/CXXModules.json")
  endif()
endforeach()
if(NOT active_maps)
  message(FATAL_ERROR "No CXX.dd provider edges in ${NINJA_FILE}")
endif()
file(GLOB candidates "${BUILD_DIR}/CMakeFiles/*/CXXModules.json")
set(maps)
foreach(map IN LISTS candidates)
  cmake_path(NORMAL_PATH map)
  if(map IN_LIST active_maps)
    list(APPEND maps "${map}")
  endif()
endforeach()
if(NOT DEFINED MODULES)
  set(MODULES native.static_string native.wide native.simd native)
endif()
foreach(module IN LISTS MODULES)
  set(providers)
  foreach(map IN LISTS maps)
    file(READ "${map}" data)
    string(JSON bmi ERROR_VARIABLE error GET "${data}" modules "${module}" bmi)
    if(NOT error)
      string(REPLACE "\\" "/" bmi "${bmi}")
      cmake_path(ABSOLUTE_PATH bmi BASE_DIRECTORY "${ninja_dir}" NORMALIZE)
      list(APPEND providers "${bmi}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES providers)
  list(LENGTH providers count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "${module}: expected one BMI, found ${count}: ${providers}")
  endif()
  foreach(bmi IN LISTS providers)
    if(NOT EXISTS "${bmi}")
      message(FATAL_ERROR "${module}: provider was not built: ${bmi}")
    endif()
  endforeach()
  message(STATUS "${module}: ${providers}")
endforeach()

# Native implementation families live in the hub; no ISA-specific BMI may be
# present in the active consumer graph.
foreach(map IN LISTS maps)
  file(READ "${map}" data)
  foreach(old IN ITEMS avx2 avx512 avx512_bf16 avx512_fp16 neon neon_fp16 neon_bf16)
    string(JSON bmi ERROR_VARIABLE error GET "${data}" modules "native.${old}" bmi)
    if(NOT error)
      message(FATAL_ERROR "Unexpected separate ISA BMI: native.${old}: ${bmi}")
    endif()
  endforeach()
endforeach()
