// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
#include <concepts>
#include <utility>
namespace rdm_simd_contract {
  constexpr auto arch_0 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_0 = requires(A... a) { native::sqrdmlah<arch_0>(a...); };
  static_assert(accepts_0<int16_t, int16_t, int16_t>);
  static_assert(std::same_as<decltype(native::sqrdmlah<arch_0>(std::declval<int16_t>(), std::declval<int16_t>(), std::declval<int16_t>())), int16_t>);
  constexpr auto arch_1 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_1 = requires(A... a) { native::sqrdmlah_lane<arch_1, 0>(a...); };
  static_assert(accepts_1<int16_t, int16_t, native::simd<std::int16_t, 4, arch_1>>);
  static_assert(!accepts_1<int16_t, int16_t, native::simd<std::uint16_t, 4, arch_1>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_1, 0>(std::declval<int16_t>(), std::declval<int16_t>(), std::declval<native::simd<std::int16_t, 4, arch_1>>())), int16_t>);
  static_assert(!accepts_1<int16_t, int16_t, int16x4_t>);
  static_assert(!accepts_1<int16_t, int16_t, native::simd<std::int16_t, 4, (arch_1 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_2 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_2 = requires(A... a) { native::sqrdmlah_lane<arch_2, 0>(a...); };
  static_assert(accepts_2<int16_t, int16_t, native::simd<std::int16_t, 8, arch_2>>);
  static_assert(!accepts_2<int16_t, int16_t, native::simd<std::uint16_t, 8, arch_2>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_2, 0>(std::declval<int16_t>(), std::declval<int16_t>(), std::declval<native::simd<std::int16_t, 8, arch_2>>())), int16_t>);
  static_assert(!accepts_2<int16_t, int16_t, int16x8_t>);
  static_assert(!accepts_2<int16_t, int16_t, native::simd<std::int16_t, 8, (arch_2 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_3 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_3 = requires(A... a) { native::sqrdmlah<arch_3>(a...); };
  static_assert(accepts_3<native::simd<std::int16_t, 4, arch_3>, native::simd<std::int16_t, 4, arch_3>, native::simd<std::int16_t, 4, arch_3>>);
  static_assert(!accepts_3<native::simd<std::uint16_t, 4, arch_3>, native::simd<std::int16_t, 4, arch_3>, native::simd<std::int16_t, 4, arch_3>>);
  static_assert(std::same_as<decltype(native::sqrdmlah<arch_3>(std::declval<native::simd<std::int16_t, 4, arch_3>>(), std::declval<native::simd<std::int16_t, 4, arch_3>>(), std::declval<native::simd<std::int16_t, 4, arch_3>>())), native::simd<std::int16_t, 4, arch_3>>);
  static_assert(!accepts_3<int16x4_t, int16x4_t, int16x4_t>);
  static_assert(!accepts_3<native::simd<std::int16_t, 4, (arch_3 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 4, arch_3>, native::simd<std::int16_t, 4, arch_3>>);
  constexpr auto arch_4 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_4 = requires(A... a) { native::sqrdmlah_lane<arch_4, 0>(a...); };
  static_assert(accepts_4<native::simd<std::int16_t, 4, arch_4>, native::simd<std::int16_t, 4, arch_4>, native::simd<std::int16_t, 4, arch_4>>);
  static_assert(!accepts_4<native::simd<std::uint16_t, 4, arch_4>, native::simd<std::int16_t, 4, arch_4>, native::simd<std::int16_t, 4, arch_4>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_4, 0>(std::declval<native::simd<std::int16_t, 4, arch_4>>(), std::declval<native::simd<std::int16_t, 4, arch_4>>(), std::declval<native::simd<std::int16_t, 4, arch_4>>())), native::simd<std::int16_t, 4, arch_4>>);
  static_assert(!accepts_4<int16x4_t, int16x4_t, int16x4_t>);
  static_assert(!accepts_4<native::simd<std::int16_t, 4, (arch_4 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 4, arch_4>, native::simd<std::int16_t, 4, arch_4>>);
  constexpr auto arch_5 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_5 = requires(A... a) { native::sqrdmlah_lane<arch_5, 0>(a...); };
  static_assert(accepts_5<native::simd<std::int16_t, 4, arch_5>, native::simd<std::int16_t, 4, arch_5>, native::simd<std::int16_t, 8, arch_5>>);
  static_assert(!accepts_5<native::simd<std::uint16_t, 4, arch_5>, native::simd<std::int16_t, 4, arch_5>, native::simd<std::int16_t, 8, arch_5>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_5, 0>(std::declval<native::simd<std::int16_t, 4, arch_5>>(), std::declval<native::simd<std::int16_t, 4, arch_5>>(), std::declval<native::simd<std::int16_t, 8, arch_5>>())), native::simd<std::int16_t, 4, arch_5>>);
  static_assert(!accepts_5<int16x4_t, int16x4_t, int16x8_t>);
  static_assert(!accepts_5<native::simd<std::int16_t, 4, (arch_5 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 4, arch_5>, native::simd<std::int16_t, 8, arch_5>>);
  constexpr auto arch_6 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_6 = requires(A... a) { native::sqrdmlah<arch_6>(a...); };
  static_assert(accepts_6<native::simd<std::int16_t, 8, arch_6>, native::simd<std::int16_t, 8, arch_6>, native::simd<std::int16_t, 8, arch_6>>);
  static_assert(!accepts_6<native::simd<std::uint16_t, 8, arch_6>, native::simd<std::int16_t, 8, arch_6>, native::simd<std::int16_t, 8, arch_6>>);
  static_assert(std::same_as<decltype(native::sqrdmlah<arch_6>(std::declval<native::simd<std::int16_t, 8, arch_6>>(), std::declval<native::simd<std::int16_t, 8, arch_6>>(), std::declval<native::simd<std::int16_t, 8, arch_6>>())), native::simd<std::int16_t, 8, arch_6>>);
  static_assert(!accepts_6<int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!accepts_6<native::simd<std::int16_t, 8, (arch_6 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 8, arch_6>, native::simd<std::int16_t, 8, arch_6>>);
  constexpr auto arch_7 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_7 = requires(A... a) { native::sqrdmlah_lane<arch_7, 0>(a...); };
  static_assert(accepts_7<native::simd<std::int16_t, 8, arch_7>, native::simd<std::int16_t, 8, arch_7>, native::simd<std::int16_t, 4, arch_7>>);
  static_assert(!accepts_7<native::simd<std::uint16_t, 8, arch_7>, native::simd<std::int16_t, 8, arch_7>, native::simd<std::int16_t, 4, arch_7>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_7, 0>(std::declval<native::simd<std::int16_t, 8, arch_7>>(), std::declval<native::simd<std::int16_t, 8, arch_7>>(), std::declval<native::simd<std::int16_t, 4, arch_7>>())), native::simd<std::int16_t, 8, arch_7>>);
  static_assert(!accepts_7<int16x8_t, int16x8_t, int16x4_t>);
  static_assert(!accepts_7<native::simd<std::int16_t, 8, (arch_7 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 8, arch_7>, native::simd<std::int16_t, 4, arch_7>>);
  constexpr auto arch_8 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_8 = requires(A... a) { native::sqrdmlah_lane<arch_8, 0>(a...); };
  static_assert(accepts_8<native::simd<std::int16_t, 8, arch_8>, native::simd<std::int16_t, 8, arch_8>, native::simd<std::int16_t, 8, arch_8>>);
  static_assert(!accepts_8<native::simd<std::uint16_t, 8, arch_8>, native::simd<std::int16_t, 8, arch_8>, native::simd<std::int16_t, 8, arch_8>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_8, 0>(std::declval<native::simd<std::int16_t, 8, arch_8>>(), std::declval<native::simd<std::int16_t, 8, arch_8>>(), std::declval<native::simd<std::int16_t, 8, arch_8>>())), native::simd<std::int16_t, 8, arch_8>>);
  static_assert(!accepts_8<int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!accepts_8<native::simd<std::int16_t, 8, (arch_8 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 8, arch_8>, native::simd<std::int16_t, 8, arch_8>>);
  constexpr auto arch_9 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_9 = requires(A... a) { native::sqrdmlah<arch_9>(a...); };
  static_assert(accepts_9<int32_t, int32_t, int32_t>);
  static_assert(std::same_as<decltype(native::sqrdmlah<arch_9>(std::declval<int32_t>(), std::declval<int32_t>(), std::declval<int32_t>())), int32_t>);
  constexpr auto arch_10 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_10 = requires(A... a) { native::sqrdmlah_lane<arch_10, 0>(a...); };
  static_assert(accepts_10<int32_t, int32_t, native::simd<std::int32_t, 2, arch_10>>);
  static_assert(!accepts_10<int32_t, int32_t, native::simd<std::uint32_t, 2, arch_10>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_10, 0>(std::declval<int32_t>(), std::declval<int32_t>(), std::declval<native::simd<std::int32_t, 2, arch_10>>())), int32_t>);
  static_assert(!accepts_10<int32_t, int32_t, int32x2_t>);
  static_assert(!accepts_10<int32_t, int32_t, native::simd<std::int32_t, 2, (arch_10 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_11 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_11 = requires(A... a) { native::sqrdmlah_lane<arch_11, 0>(a...); };
  static_assert(accepts_11<int32_t, int32_t, native::simd<std::int32_t, 4, arch_11>>);
  static_assert(!accepts_11<int32_t, int32_t, native::simd<std::uint32_t, 4, arch_11>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_11, 0>(std::declval<int32_t>(), std::declval<int32_t>(), std::declval<native::simd<std::int32_t, 4, arch_11>>())), int32_t>);
  static_assert(!accepts_11<int32_t, int32_t, int32x4_t>);
  static_assert(!accepts_11<int32_t, int32_t, native::simd<std::int32_t, 4, (arch_11 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_12 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_12 = requires(A... a) { native::sqrdmlah<arch_12>(a...); };
  static_assert(accepts_12<native::simd<std::int32_t, 2, arch_12>, native::simd<std::int32_t, 2, arch_12>, native::simd<std::int32_t, 2, arch_12>>);
  static_assert(!accepts_12<native::simd<std::uint32_t, 2, arch_12>, native::simd<std::int32_t, 2, arch_12>, native::simd<std::int32_t, 2, arch_12>>);
  static_assert(std::same_as<decltype(native::sqrdmlah<arch_12>(std::declval<native::simd<std::int32_t, 2, arch_12>>(), std::declval<native::simd<std::int32_t, 2, arch_12>>(), std::declval<native::simd<std::int32_t, 2, arch_12>>())), native::simd<std::int32_t, 2, arch_12>>);
  static_assert(!accepts_12<int32x2_t, int32x2_t, int32x2_t>);
  static_assert(!accepts_12<native::simd<std::int32_t, 2, (arch_12 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 2, arch_12>, native::simd<std::int32_t, 2, arch_12>>);
  constexpr auto arch_13 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_13 = requires(A... a) { native::sqrdmlah_lane<arch_13, 0>(a...); };
  static_assert(accepts_13<native::simd<std::int32_t, 2, arch_13>, native::simd<std::int32_t, 2, arch_13>, native::simd<std::int32_t, 2, arch_13>>);
  static_assert(!accepts_13<native::simd<std::uint32_t, 2, arch_13>, native::simd<std::int32_t, 2, arch_13>, native::simd<std::int32_t, 2, arch_13>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_13, 0>(std::declval<native::simd<std::int32_t, 2, arch_13>>(), std::declval<native::simd<std::int32_t, 2, arch_13>>(), std::declval<native::simd<std::int32_t, 2, arch_13>>())), native::simd<std::int32_t, 2, arch_13>>);
  static_assert(!accepts_13<int32x2_t, int32x2_t, int32x2_t>);
  static_assert(!accepts_13<native::simd<std::int32_t, 2, (arch_13 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 2, arch_13>, native::simd<std::int32_t, 2, arch_13>>);
  constexpr auto arch_14 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_14 = requires(A... a) { native::sqrdmlah_lane<arch_14, 0>(a...); };
  static_assert(accepts_14<native::simd<std::int32_t, 2, arch_14>, native::simd<std::int32_t, 2, arch_14>, native::simd<std::int32_t, 4, arch_14>>);
  static_assert(!accepts_14<native::simd<std::uint32_t, 2, arch_14>, native::simd<std::int32_t, 2, arch_14>, native::simd<std::int32_t, 4, arch_14>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_14, 0>(std::declval<native::simd<std::int32_t, 2, arch_14>>(), std::declval<native::simd<std::int32_t, 2, arch_14>>(), std::declval<native::simd<std::int32_t, 4, arch_14>>())), native::simd<std::int32_t, 2, arch_14>>);
  static_assert(!accepts_14<int32x2_t, int32x2_t, int32x4_t>);
  static_assert(!accepts_14<native::simd<std::int32_t, 2, (arch_14 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 2, arch_14>, native::simd<std::int32_t, 4, arch_14>>);
  constexpr auto arch_15 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_15 = requires(A... a) { native::sqrdmlah<arch_15>(a...); };
  static_assert(accepts_15<native::simd<std::int32_t, 4, arch_15>, native::simd<std::int32_t, 4, arch_15>, native::simd<std::int32_t, 4, arch_15>>);
  static_assert(!accepts_15<native::simd<std::uint32_t, 4, arch_15>, native::simd<std::int32_t, 4, arch_15>, native::simd<std::int32_t, 4, arch_15>>);
  static_assert(std::same_as<decltype(native::sqrdmlah<arch_15>(std::declval<native::simd<std::int32_t, 4, arch_15>>(), std::declval<native::simd<std::int32_t, 4, arch_15>>(), std::declval<native::simd<std::int32_t, 4, arch_15>>())), native::simd<std::int32_t, 4, arch_15>>);
  static_assert(!accepts_15<int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!accepts_15<native::simd<std::int32_t, 4, (arch_15 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 4, arch_15>, native::simd<std::int32_t, 4, arch_15>>);
  constexpr auto arch_16 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_16 = requires(A... a) { native::sqrdmlah_lane<arch_16, 0>(a...); };
  static_assert(accepts_16<native::simd<std::int32_t, 4, arch_16>, native::simd<std::int32_t, 4, arch_16>, native::simd<std::int32_t, 2, arch_16>>);
  static_assert(!accepts_16<native::simd<std::uint32_t, 4, arch_16>, native::simd<std::int32_t, 4, arch_16>, native::simd<std::int32_t, 2, arch_16>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_16, 0>(std::declval<native::simd<std::int32_t, 4, arch_16>>(), std::declval<native::simd<std::int32_t, 4, arch_16>>(), std::declval<native::simd<std::int32_t, 2, arch_16>>())), native::simd<std::int32_t, 4, arch_16>>);
  static_assert(!accepts_16<int32x4_t, int32x4_t, int32x2_t>);
  static_assert(!accepts_16<native::simd<std::int32_t, 4, (arch_16 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 4, arch_16>, native::simd<std::int32_t, 2, arch_16>>);
  constexpr auto arch_17 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_17 = requires(A... a) { native::sqrdmlah_lane<arch_17, 0>(a...); };
  static_assert(accepts_17<native::simd<std::int32_t, 4, arch_17>, native::simd<std::int32_t, 4, arch_17>, native::simd<std::int32_t, 4, arch_17>>);
  static_assert(!accepts_17<native::simd<std::uint32_t, 4, arch_17>, native::simd<std::int32_t, 4, arch_17>, native::simd<std::int32_t, 4, arch_17>>);
  static_assert(std::same_as<decltype(native::sqrdmlah_lane<arch_17, 0>(std::declval<native::simd<std::int32_t, 4, arch_17>>(), std::declval<native::simd<std::int32_t, 4, arch_17>>(), std::declval<native::simd<std::int32_t, 4, arch_17>>())), native::simd<std::int32_t, 4, arch_17>>);
  static_assert(!accepts_17<int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!accepts_17<native::simd<std::int32_t, 4, (arch_17 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 4, arch_17>, native::simd<std::int32_t, 4, arch_17>>);
  constexpr auto arch_18 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_18 = requires(A... a) { native::sqrdmlsh<arch_18>(a...); };
  static_assert(accepts_18<int16_t, int16_t, int16_t>);
  static_assert(std::same_as<decltype(native::sqrdmlsh<arch_18>(std::declval<int16_t>(), std::declval<int16_t>(), std::declval<int16_t>())), int16_t>);
  constexpr auto arch_19 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_19 = requires(A... a) { native::sqrdmlsh_lane<arch_19, 0>(a...); };
  static_assert(accepts_19<int16_t, int16_t, native::simd<std::int16_t, 4, arch_19>>);
  static_assert(!accepts_19<int16_t, int16_t, native::simd<std::uint16_t, 4, arch_19>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_19, 0>(std::declval<int16_t>(), std::declval<int16_t>(), std::declval<native::simd<std::int16_t, 4, arch_19>>())), int16_t>);
  static_assert(!accepts_19<int16_t, int16_t, int16x4_t>);
  static_assert(!accepts_19<int16_t, int16_t, native::simd<std::int16_t, 4, (arch_19 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_20 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_20 = requires(A... a) { native::sqrdmlsh_lane<arch_20, 0>(a...); };
  static_assert(accepts_20<int16_t, int16_t, native::simd<std::int16_t, 8, arch_20>>);
  static_assert(!accepts_20<int16_t, int16_t, native::simd<std::uint16_t, 8, arch_20>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_20, 0>(std::declval<int16_t>(), std::declval<int16_t>(), std::declval<native::simd<std::int16_t, 8, arch_20>>())), int16_t>);
  static_assert(!accepts_20<int16_t, int16_t, int16x8_t>);
  static_assert(!accepts_20<int16_t, int16_t, native::simd<std::int16_t, 8, (arch_20 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_21 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_21 = requires(A... a) { native::sqrdmlsh<arch_21>(a...); };
  static_assert(accepts_21<native::simd<std::int16_t, 4, arch_21>, native::simd<std::int16_t, 4, arch_21>, native::simd<std::int16_t, 4, arch_21>>);
  static_assert(!accepts_21<native::simd<std::uint16_t, 4, arch_21>, native::simd<std::int16_t, 4, arch_21>, native::simd<std::int16_t, 4, arch_21>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh<arch_21>(std::declval<native::simd<std::int16_t, 4, arch_21>>(), std::declval<native::simd<std::int16_t, 4, arch_21>>(), std::declval<native::simd<std::int16_t, 4, arch_21>>())), native::simd<std::int16_t, 4, arch_21>>);
  static_assert(!accepts_21<int16x4_t, int16x4_t, int16x4_t>);
  static_assert(!accepts_21<native::simd<std::int16_t, 4, (arch_21 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 4, arch_21>, native::simd<std::int16_t, 4, arch_21>>);
  constexpr auto arch_22 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_22 = requires(A... a) { native::sqrdmlsh_lane<arch_22, 0>(a...); };
  static_assert(accepts_22<native::simd<std::int16_t, 4, arch_22>, native::simd<std::int16_t, 4, arch_22>, native::simd<std::int16_t, 4, arch_22>>);
  static_assert(!accepts_22<native::simd<std::uint16_t, 4, arch_22>, native::simd<std::int16_t, 4, arch_22>, native::simd<std::int16_t, 4, arch_22>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_22, 0>(std::declval<native::simd<std::int16_t, 4, arch_22>>(), std::declval<native::simd<std::int16_t, 4, arch_22>>(), std::declval<native::simd<std::int16_t, 4, arch_22>>())), native::simd<std::int16_t, 4, arch_22>>);
  static_assert(!accepts_22<int16x4_t, int16x4_t, int16x4_t>);
  static_assert(!accepts_22<native::simd<std::int16_t, 4, (arch_22 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 4, arch_22>, native::simd<std::int16_t, 4, arch_22>>);
  constexpr auto arch_23 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_23 = requires(A... a) { native::sqrdmlsh_lane<arch_23, 0>(a...); };
  static_assert(accepts_23<native::simd<std::int16_t, 4, arch_23>, native::simd<std::int16_t, 4, arch_23>, native::simd<std::int16_t, 8, arch_23>>);
  static_assert(!accepts_23<native::simd<std::uint16_t, 4, arch_23>, native::simd<std::int16_t, 4, arch_23>, native::simd<std::int16_t, 8, arch_23>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_23, 0>(std::declval<native::simd<std::int16_t, 4, arch_23>>(), std::declval<native::simd<std::int16_t, 4, arch_23>>(), std::declval<native::simd<std::int16_t, 8, arch_23>>())), native::simd<std::int16_t, 4, arch_23>>);
  static_assert(!accepts_23<int16x4_t, int16x4_t, int16x8_t>);
  static_assert(!accepts_23<native::simd<std::int16_t, 4, (arch_23 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 4, arch_23>, native::simd<std::int16_t, 8, arch_23>>);
  constexpr auto arch_24 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_24 = requires(A... a) { native::sqrdmlsh<arch_24>(a...); };
  static_assert(accepts_24<native::simd<std::int16_t, 8, arch_24>, native::simd<std::int16_t, 8, arch_24>, native::simd<std::int16_t, 8, arch_24>>);
  static_assert(!accepts_24<native::simd<std::uint16_t, 8, arch_24>, native::simd<std::int16_t, 8, arch_24>, native::simd<std::int16_t, 8, arch_24>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh<arch_24>(std::declval<native::simd<std::int16_t, 8, arch_24>>(), std::declval<native::simd<std::int16_t, 8, arch_24>>(), std::declval<native::simd<std::int16_t, 8, arch_24>>())), native::simd<std::int16_t, 8, arch_24>>);
  static_assert(!accepts_24<int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!accepts_24<native::simd<std::int16_t, 8, (arch_24 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 8, arch_24>, native::simd<std::int16_t, 8, arch_24>>);
  constexpr auto arch_25 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_25 = requires(A... a) { native::sqrdmlsh_lane<arch_25, 0>(a...); };
  static_assert(accepts_25<native::simd<std::int16_t, 8, arch_25>, native::simd<std::int16_t, 8, arch_25>, native::simd<std::int16_t, 4, arch_25>>);
  static_assert(!accepts_25<native::simd<std::uint16_t, 8, arch_25>, native::simd<std::int16_t, 8, arch_25>, native::simd<std::int16_t, 4, arch_25>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_25, 0>(std::declval<native::simd<std::int16_t, 8, arch_25>>(), std::declval<native::simd<std::int16_t, 8, arch_25>>(), std::declval<native::simd<std::int16_t, 4, arch_25>>())), native::simd<std::int16_t, 8, arch_25>>);
  static_assert(!accepts_25<int16x8_t, int16x8_t, int16x4_t>);
  static_assert(!accepts_25<native::simd<std::int16_t, 8, (arch_25 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 8, arch_25>, native::simd<std::int16_t, 4, arch_25>>);
  constexpr auto arch_26 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_26 = requires(A... a) { native::sqrdmlsh_lane<arch_26, 0>(a...); };
  static_assert(accepts_26<native::simd<std::int16_t, 8, arch_26>, native::simd<std::int16_t, 8, arch_26>, native::simd<std::int16_t, 8, arch_26>>);
  static_assert(!accepts_26<native::simd<std::uint16_t, 8, arch_26>, native::simd<std::int16_t, 8, arch_26>, native::simd<std::int16_t, 8, arch_26>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_26, 0>(std::declval<native::simd<std::int16_t, 8, arch_26>>(), std::declval<native::simd<std::int16_t, 8, arch_26>>(), std::declval<native::simd<std::int16_t, 8, arch_26>>())), native::simd<std::int16_t, 8, arch_26>>);
  static_assert(!accepts_26<int16x8_t, int16x8_t, int16x8_t>);
  static_assert(!accepts_26<native::simd<std::int16_t, 8, (arch_26 & native::isa(native::arm_feature::crc))>, native::simd<std::int16_t, 8, arch_26>, native::simd<std::int16_t, 8, arch_26>>);
  constexpr auto arch_27 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_27 = requires(A... a) { native::sqrdmlsh<arch_27>(a...); };
  static_assert(accepts_27<int32_t, int32_t, int32_t>);
  static_assert(std::same_as<decltype(native::sqrdmlsh<arch_27>(std::declval<int32_t>(), std::declval<int32_t>(), std::declval<int32_t>())), int32_t>);
  constexpr auto arch_28 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_28 = requires(A... a) { native::sqrdmlsh_lane<arch_28, 0>(a...); };
  static_assert(accepts_28<int32_t, int32_t, native::simd<std::int32_t, 2, arch_28>>);
  static_assert(!accepts_28<int32_t, int32_t, native::simd<std::uint32_t, 2, arch_28>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_28, 0>(std::declval<int32_t>(), std::declval<int32_t>(), std::declval<native::simd<std::int32_t, 2, arch_28>>())), int32_t>);
  static_assert(!accepts_28<int32_t, int32_t, int32x2_t>);
  static_assert(!accepts_28<int32_t, int32_t, native::simd<std::int32_t, 2, (arch_28 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_29 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_29 = requires(A... a) { native::sqrdmlsh_lane<arch_29, 0>(a...); };
  static_assert(accepts_29<int32_t, int32_t, native::simd<std::int32_t, 4, arch_29>>);
  static_assert(!accepts_29<int32_t, int32_t, native::simd<std::uint32_t, 4, arch_29>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_29, 0>(std::declval<int32_t>(), std::declval<int32_t>(), std::declval<native::simd<std::int32_t, 4, arch_29>>())), int32_t>);
  static_assert(!accepts_29<int32_t, int32_t, int32x4_t>);
  static_assert(!accepts_29<int32_t, int32_t, native::simd<std::int32_t, 4, (arch_29 & native::isa(native::arm_feature::crc))>>);
  constexpr auto arch_30 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_30 = requires(A... a) { native::sqrdmlsh<arch_30>(a...); };
  static_assert(accepts_30<native::simd<std::int32_t, 2, arch_30>, native::simd<std::int32_t, 2, arch_30>, native::simd<std::int32_t, 2, arch_30>>);
  static_assert(!accepts_30<native::simd<std::uint32_t, 2, arch_30>, native::simd<std::int32_t, 2, arch_30>, native::simd<std::int32_t, 2, arch_30>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh<arch_30>(std::declval<native::simd<std::int32_t, 2, arch_30>>(), std::declval<native::simd<std::int32_t, 2, arch_30>>(), std::declval<native::simd<std::int32_t, 2, arch_30>>())), native::simd<std::int32_t, 2, arch_30>>);
  static_assert(!accepts_30<int32x2_t, int32x2_t, int32x2_t>);
  static_assert(!accepts_30<native::simd<std::int32_t, 2, (arch_30 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 2, arch_30>, native::simd<std::int32_t, 2, arch_30>>);
  constexpr auto arch_31 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_31 = requires(A... a) { native::sqrdmlsh_lane<arch_31, 0>(a...); };
  static_assert(accepts_31<native::simd<std::int32_t, 2, arch_31>, native::simd<std::int32_t, 2, arch_31>, native::simd<std::int32_t, 2, arch_31>>);
  static_assert(!accepts_31<native::simd<std::uint32_t, 2, arch_31>, native::simd<std::int32_t, 2, arch_31>, native::simd<std::int32_t, 2, arch_31>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_31, 0>(std::declval<native::simd<std::int32_t, 2, arch_31>>(), std::declval<native::simd<std::int32_t, 2, arch_31>>(), std::declval<native::simd<std::int32_t, 2, arch_31>>())), native::simd<std::int32_t, 2, arch_31>>);
  static_assert(!accepts_31<int32x2_t, int32x2_t, int32x2_t>);
  static_assert(!accepts_31<native::simd<std::int32_t, 2, (arch_31 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 2, arch_31>, native::simd<std::int32_t, 2, arch_31>>);
  constexpr auto arch_32 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_32 = requires(A... a) { native::sqrdmlsh_lane<arch_32, 0>(a...); };
  static_assert(accepts_32<native::simd<std::int32_t, 2, arch_32>, native::simd<std::int32_t, 2, arch_32>, native::simd<std::int32_t, 4, arch_32>>);
  static_assert(!accepts_32<native::simd<std::uint32_t, 2, arch_32>, native::simd<std::int32_t, 2, arch_32>, native::simd<std::int32_t, 4, arch_32>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_32, 0>(std::declval<native::simd<std::int32_t, 2, arch_32>>(), std::declval<native::simd<std::int32_t, 2, arch_32>>(), std::declval<native::simd<std::int32_t, 4, arch_32>>())), native::simd<std::int32_t, 2, arch_32>>);
  static_assert(!accepts_32<int32x2_t, int32x2_t, int32x4_t>);
  static_assert(!accepts_32<native::simd<std::int32_t, 2, (arch_32 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 2, arch_32>, native::simd<std::int32_t, 4, arch_32>>);
  constexpr auto arch_33 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_33 = requires(A... a) { native::sqrdmlsh<arch_33>(a...); };
  static_assert(accepts_33<native::simd<std::int32_t, 4, arch_33>, native::simd<std::int32_t, 4, arch_33>, native::simd<std::int32_t, 4, arch_33>>);
  static_assert(!accepts_33<native::simd<std::uint32_t, 4, arch_33>, native::simd<std::int32_t, 4, arch_33>, native::simd<std::int32_t, 4, arch_33>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh<arch_33>(std::declval<native::simd<std::int32_t, 4, arch_33>>(), std::declval<native::simd<std::int32_t, 4, arch_33>>(), std::declval<native::simd<std::int32_t, 4, arch_33>>())), native::simd<std::int32_t, 4, arch_33>>);
  static_assert(!accepts_33<int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!accepts_33<native::simd<std::int32_t, 4, (arch_33 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 4, arch_33>, native::simd<std::int32_t, 4, arch_33>>);
  constexpr auto arch_34 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_34 = requires(A... a) { native::sqrdmlsh_lane<arch_34, 0>(a...); };
  static_assert(accepts_34<native::simd<std::int32_t, 4, arch_34>, native::simd<std::int32_t, 4, arch_34>, native::simd<std::int32_t, 2, arch_34>>);
  static_assert(!accepts_34<native::simd<std::uint32_t, 4, arch_34>, native::simd<std::int32_t, 4, arch_34>, native::simd<std::int32_t, 2, arch_34>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_34, 0>(std::declval<native::simd<std::int32_t, 4, arch_34>>(), std::declval<native::simd<std::int32_t, 4, arch_34>>(), std::declval<native::simd<std::int32_t, 2, arch_34>>())), native::simd<std::int32_t, 4, arch_34>>);
  static_assert(!accepts_34<int32x4_t, int32x4_t, int32x2_t>);
  static_assert(!accepts_34<native::simd<std::int32_t, 4, (arch_34 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 4, arch_34>, native::simd<std::int32_t, 2, arch_34>>);
  constexpr auto arch_35 = native::feature_closure(native::isa(native::arm_feature::rdm));
  template<class... A> concept accepts_35 = requires(A... a) { native::sqrdmlsh_lane<arch_35, 0>(a...); };
  static_assert(accepts_35<native::simd<std::int32_t, 4, arch_35>, native::simd<std::int32_t, 4, arch_35>, native::simd<std::int32_t, 4, arch_35>>);
  static_assert(!accepts_35<native::simd<std::uint32_t, 4, arch_35>, native::simd<std::int32_t, 4, arch_35>, native::simd<std::int32_t, 4, arch_35>>);
  static_assert(std::same_as<decltype(native::sqrdmlsh_lane<arch_35, 0>(std::declval<native::simd<std::int32_t, 4, arch_35>>(), std::declval<native::simd<std::int32_t, 4, arch_35>>(), std::declval<native::simd<std::int32_t, 4, arch_35>>())), native::simd<std::int32_t, 4, arch_35>>);
  static_assert(!accepts_35<int32x4_t, int32x4_t, int32x4_t>);
  static_assert(!accepts_35<native::simd<std::int32_t, 4, (arch_35 & native::isa(native::arm_feature::crc))>, native::simd<std::int32_t, 4, arch_35>, native::simd<std::int32_t, 4, arch_35>>);
}
