# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
"""Exact-rational BF16 matrix and fused multiply-add references; AH=FIZ=0.

Reuse the separately tested BFDOT arithmetic oracle, not native instructions.
Matrices use two ordered pair accumulations per result. Fused multiply-add
has one final rounding and default NaNs (the fixture sets DN=1).
"""
from pathlib import Path
import argparse
import importlib.util
import random

source = Path(__file__).parent.parent / 'neon_bf16' / 'generate_reference.py'
spec = importlib.util.spec_from_file_location('dot_oracle', source)
oracle = importlib.util.module_from_spec(spec)
spec.loader.exec_module(oracle)

begin_marker = b'// BEGIN GENERATED ARM BF16 REFERENCE\n'
end_marker = b'// END GENERATED ARM BF16 REFERENCE\n'


def split_region(source):
    if source.count(begin_marker) != 1 or source.count(end_marker) != 1:
        raise ValueError('Expected one marked ARM BF16 reference region')
    prefix, remaining = source.split(begin_marker)
    generated, suffix = remaining.split(end_marker)
    return prefix + begin_marker, generated, end_marker + suffix


def matrix(a, b, c, enhanced=False, mode='RNE', flush=False):
    result = []
    for row in range(2):
        for column in range(2):
            value = c[2*row + column]
            for pair in range(2):
                ai, bi = 4*row + 2*pair, 4*column + 2*pair
                value = oracle.dot((*a[ai:ai+2], *b[bi:bi+2], value), enhanced, mode, flush)
            result.append(value)
    return result


def fused(a, b, c, mode, flush):
    product = oracle.product(oracle.unpack(a << 16, flush), oracle.unpack(b << 16, flush))
    value = oracle.addition(oracle.unpack(c, flush), product, mode)
    return oracle.pack(value, mode, flush)


def words(values, digits=8):
    return '{' + ','.join(f'0x{x:0{digits}x}' for x in values) + '}'


def generate():
    checks = oracle.self_check()
    # Known matrix layout and association controls, independent of the loops.
    one, two, three, four = 0x3f80, 0x4000, 0x4040, 0x4080
    assert matrix([one]*8, [one]*8, [0]*4) == [0x40800000]*4
    assert matrix([one,0,0,0,0,two,0,0], [three,0,0,0,0,four,0,0], [0]*4) == [0x40400000,0,0,0x41000000]
    assert fused(one, one, 0xbf800000, 'RNE', False) == 0
    assert fused(one, one, 0xbf800000, 'RDN', False) == 0x80000000
    rng = random.Random(0xbf1642)
    special = [0,1,0x7f,0x80,0x81,0x3f00,one,0x3f81,0x7f7f,0x7f80,0x7f81,0x7fc1]
    special += [x | 0x8000 for x in special]
    matrices = []
    for i in range(8):
        for j in range(8):
            a, b = [0]*8, [0]*8
            a[i], b[j] = one, two
            matrices.append((a,b,[0]*4))
    # First pair produces a rounded accumulator used by the second pair.
    matrices.append(([0x3f80,0xc580,0x3f80,0,0x7f7f,0xff7f,one,0],
                     [one,0x4580,one,0,0x4000,0x4000,one,0], [0x4b800000,0,0,0]))
    while len(matrices) < 512:
        if len(matrices) < 256:
            a, b = [[rng.choice(special) for _ in range(8)] for _ in range(2)]
        else:
            a, b = [[rng.getrandbits(16) for _ in range(8)] for _ in range(2)]
        matrices.append((a,b,[rng.getrandbits(32) for _ in range(4)]))
    fmas = [(one,one,0xbf800000), (0x0080,0x3f7f,0), (0x7f7f,0x4000,0),
            (one,0x3380,0x3f800000), (0x8000,one,0x80000000)]
    while len(fmas)<512:
        a,b = [rng.choice(special) if len(fmas)<256 else rng.getrandbits(16) for _ in range(2)]
        fmas.append((a,b,rng.getrandbits(32)))
    text='''// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
// Generated by generate_reference.py using exact rational arithmetic.
#include <cstdint>
namespace arm_bf16_reference {
  struct matrix_sample {std::uint16_t a[8],b[8]; std::uint32_t acc[4],result[9][4];};
  inline constexpr matrix_sample matrices[] = {
'''
    for a,b,c in matrices:
        results=[matrix(a,b,c)]+[matrix(a,b,c,True,m,f) for m in oracle.MODES for f in (False,True)]
        text+='    {'+','.join([words(a,4),words(b,4),words(c),'{'+','.join(words(r) for r in results)+'}'])+'},\n'
    text+='''  };
  struct fma_sample {std::uint16_t a,b; std::uint32_t acc,result[8];};
  inline constexpr fma_sample fmas[] = {
'''
    for a,b,c in fmas:
        results=[fused(a,b,c,m,f) for m in oracle.MODES for f in (False,True)]
        text+=f'    {{0x{a:04x},0x{b:04x},0x{c:08x},'+words(results)+'},\n'
    text+='  };\n}\n'
    print(f'{checks+4} oracle self-checks; {len(matrices)} matrices and {len(fmas)} fused cases')
    return text.encode('utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path,
                        help='Write the generated region to this file instead of updating checks.h')
    output = parser.parse_args().output
    if output is not None:
        output.write_bytes(generate())
    else:
        consumer = Path(__file__).with_name('checks.h')
        prefix, _, suffix = split_region(consumer.read_bytes())
        consumer.write_bytes(prefix + generate() + suffix)
