// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
#include <concepts>
#include <utility>
namespace dotprod_simd_contract {
  constexpr auto arch_0 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_0 = requires(A... a) { native::sdot<arch_0>(a...); };
  static_assert(accepts_0<native::simd<std::int32_t, 2, arch_0>, native::simd<std::int8_t, 8, arch_0>, native::simd<std::int8_t, 8, arch_0>>);
  static_assert(!accepts_0<native::simd<std::uint32_t, 2, arch_0>, native::simd<std::int8_t, 8, arch_0>, native::simd<std::int8_t, 8, arch_0>>);
  static_assert(std::same_as<decltype(native::sdot<arch_0>(std::declval<native::simd<std::int32_t, 2, arch_0>>(), std::declval<native::simd<std::int8_t, 8, arch_0>>(), std::declval<native::simd<std::int8_t, 8, arch_0>>())), native::simd<std::int32_t, 2, arch_0>>);
  static_assert(!accepts_0<int32x2_t, int8x8_t, int8x8_t>);
  static_assert(!accepts_0<native::simd<std::int32_t, 2, (arch_0 & native::isa(native::arm_feature::crc))>, native::simd<std::int8_t, 8, arch_0>, native::simd<std::int8_t, 8, arch_0>>);
  constexpr auto arch_1 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_1 = requires(A... a) { native::sdot_lane<arch_1, 0>(a...); };
  static_assert(accepts_1<native::simd<std::int32_t, 2, arch_1>, native::simd<std::int8_t, 8, arch_1>, native::simd<std::int8_t, 8, arch_1>>);
  static_assert(!accepts_1<native::simd<std::uint32_t, 2, arch_1>, native::simd<std::int8_t, 8, arch_1>, native::simd<std::int8_t, 8, arch_1>>);
  static_assert(std::same_as<decltype(native::sdot_lane<arch_1, 0>(std::declval<native::simd<std::int32_t, 2, arch_1>>(), std::declval<native::simd<std::int8_t, 8, arch_1>>(), std::declval<native::simd<std::int8_t, 8, arch_1>>())), native::simd<std::int32_t, 2, arch_1>>);
  static_assert(!accepts_1<int32x2_t, int8x8_t, int8x8_t>);
  static_assert(!accepts_1<native::simd<std::int32_t, 2, (arch_1 & native::isa(native::arm_feature::crc))>, native::simd<std::int8_t, 8, arch_1>, native::simd<std::int8_t, 8, arch_1>>);
  constexpr auto arch_2 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_2 = requires(A... a) { native::sdot_lane<arch_2, 0>(a...); };
  static_assert(accepts_2<native::simd<std::int32_t, 2, arch_2>, native::simd<std::int8_t, 8, arch_2>, native::simd<std::int8_t, 16, arch_2>>);
  static_assert(!accepts_2<native::simd<std::uint32_t, 2, arch_2>, native::simd<std::int8_t, 8, arch_2>, native::simd<std::int8_t, 16, arch_2>>);
  static_assert(std::same_as<decltype(native::sdot_lane<arch_2, 0>(std::declval<native::simd<std::int32_t, 2, arch_2>>(), std::declval<native::simd<std::int8_t, 8, arch_2>>(), std::declval<native::simd<std::int8_t, 16, arch_2>>())), native::simd<std::int32_t, 2, arch_2>>);
  static_assert(!accepts_2<int32x2_t, int8x8_t, int8x16_t>);
  static_assert(!accepts_2<native::simd<std::int32_t, 2, (arch_2 & native::isa(native::arm_feature::crc))>, native::simd<std::int8_t, 8, arch_2>, native::simd<std::int8_t, 16, arch_2>>);
  constexpr auto arch_3 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_3 = requires(A... a) { native::sdot<arch_3>(a...); };
  static_assert(accepts_3<native::simd<std::int32_t, 4, arch_3>, native::simd<std::int8_t, 16, arch_3>, native::simd<std::int8_t, 16, arch_3>>);
  static_assert(!accepts_3<native::simd<std::uint32_t, 4, arch_3>, native::simd<std::int8_t, 16, arch_3>, native::simd<std::int8_t, 16, arch_3>>);
  static_assert(std::same_as<decltype(native::sdot<arch_3>(std::declval<native::simd<std::int32_t, 4, arch_3>>(), std::declval<native::simd<std::int8_t, 16, arch_3>>(), std::declval<native::simd<std::int8_t, 16, arch_3>>())), native::simd<std::int32_t, 4, arch_3>>);
  static_assert(!accepts_3<int32x4_t, int8x16_t, int8x16_t>);
  static_assert(!accepts_3<native::simd<std::int32_t, 4, (arch_3 & native::isa(native::arm_feature::crc))>, native::simd<std::int8_t, 16, arch_3>, native::simd<std::int8_t, 16, arch_3>>);
  constexpr auto arch_4 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_4 = requires(A... a) { native::sdot_lane<arch_4, 0>(a...); };
  static_assert(accepts_4<native::simd<std::int32_t, 4, arch_4>, native::simd<std::int8_t, 16, arch_4>, native::simd<std::int8_t, 8, arch_4>>);
  static_assert(!accepts_4<native::simd<std::uint32_t, 4, arch_4>, native::simd<std::int8_t, 16, arch_4>, native::simd<std::int8_t, 8, arch_4>>);
  static_assert(std::same_as<decltype(native::sdot_lane<arch_4, 0>(std::declval<native::simd<std::int32_t, 4, arch_4>>(), std::declval<native::simd<std::int8_t, 16, arch_4>>(), std::declval<native::simd<std::int8_t, 8, arch_4>>())), native::simd<std::int32_t, 4, arch_4>>);
  static_assert(!accepts_4<int32x4_t, int8x16_t, int8x8_t>);
  static_assert(!accepts_4<native::simd<std::int32_t, 4, (arch_4 & native::isa(native::arm_feature::crc))>, native::simd<std::int8_t, 16, arch_4>, native::simd<std::int8_t, 8, arch_4>>);
  constexpr auto arch_5 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_5 = requires(A... a) { native::sdot_lane<arch_5, 0>(a...); };
  static_assert(accepts_5<native::simd<std::int32_t, 4, arch_5>, native::simd<std::int8_t, 16, arch_5>, native::simd<std::int8_t, 16, arch_5>>);
  static_assert(!accepts_5<native::simd<std::uint32_t, 4, arch_5>, native::simd<std::int8_t, 16, arch_5>, native::simd<std::int8_t, 16, arch_5>>);
  static_assert(std::same_as<decltype(native::sdot_lane<arch_5, 0>(std::declval<native::simd<std::int32_t, 4, arch_5>>(), std::declval<native::simd<std::int8_t, 16, arch_5>>(), std::declval<native::simd<std::int8_t, 16, arch_5>>())), native::simd<std::int32_t, 4, arch_5>>);
  static_assert(!accepts_5<int32x4_t, int8x16_t, int8x16_t>);
  static_assert(!accepts_5<native::simd<std::int32_t, 4, (arch_5 & native::isa(native::arm_feature::crc))>, native::simd<std::int8_t, 16, arch_5>, native::simd<std::int8_t, 16, arch_5>>);
  constexpr auto arch_6 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_6 = requires(A... a) { native::udot<arch_6>(a...); };
  static_assert(accepts_6<native::simd<std::uint32_t, 2, arch_6>, native::simd<std::uint8_t, 8, arch_6>, native::simd<std::uint8_t, 8, arch_6>>);
  static_assert(!accepts_6<native::simd<std::int32_t, 2, arch_6>, native::simd<std::uint8_t, 8, arch_6>, native::simd<std::uint8_t, 8, arch_6>>);
  static_assert(std::same_as<decltype(native::udot<arch_6>(std::declval<native::simd<std::uint32_t, 2, arch_6>>(), std::declval<native::simd<std::uint8_t, 8, arch_6>>(), std::declval<native::simd<std::uint8_t, 8, arch_6>>())), native::simd<std::uint32_t, 2, arch_6>>);
  static_assert(!accepts_6<uint32x2_t, uint8x8_t, uint8x8_t>);
  static_assert(!accepts_6<native::simd<std::uint32_t, 2, (arch_6 & native::isa(native::arm_feature::crc))>, native::simd<std::uint8_t, 8, arch_6>, native::simd<std::uint8_t, 8, arch_6>>);
  constexpr auto arch_7 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_7 = requires(A... a) { native::udot_lane<arch_7, 0>(a...); };
  static_assert(accepts_7<native::simd<std::uint32_t, 2, arch_7>, native::simd<std::uint8_t, 8, arch_7>, native::simd<std::uint8_t, 8, arch_7>>);
  static_assert(!accepts_7<native::simd<std::int32_t, 2, arch_7>, native::simd<std::uint8_t, 8, arch_7>, native::simd<std::uint8_t, 8, arch_7>>);
  static_assert(std::same_as<decltype(native::udot_lane<arch_7, 0>(std::declval<native::simd<std::uint32_t, 2, arch_7>>(), std::declval<native::simd<std::uint8_t, 8, arch_7>>(), std::declval<native::simd<std::uint8_t, 8, arch_7>>())), native::simd<std::uint32_t, 2, arch_7>>);
  static_assert(!accepts_7<uint32x2_t, uint8x8_t, uint8x8_t>);
  static_assert(!accepts_7<native::simd<std::uint32_t, 2, (arch_7 & native::isa(native::arm_feature::crc))>, native::simd<std::uint8_t, 8, arch_7>, native::simd<std::uint8_t, 8, arch_7>>);
  constexpr auto arch_8 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_8 = requires(A... a) { native::udot_lane<arch_8, 0>(a...); };
  static_assert(accepts_8<native::simd<std::uint32_t, 2, arch_8>, native::simd<std::uint8_t, 8, arch_8>, native::simd<std::uint8_t, 16, arch_8>>);
  static_assert(!accepts_8<native::simd<std::int32_t, 2, arch_8>, native::simd<std::uint8_t, 8, arch_8>, native::simd<std::uint8_t, 16, arch_8>>);
  static_assert(std::same_as<decltype(native::udot_lane<arch_8, 0>(std::declval<native::simd<std::uint32_t, 2, arch_8>>(), std::declval<native::simd<std::uint8_t, 8, arch_8>>(), std::declval<native::simd<std::uint8_t, 16, arch_8>>())), native::simd<std::uint32_t, 2, arch_8>>);
  static_assert(!accepts_8<uint32x2_t, uint8x8_t, uint8x16_t>);
  static_assert(!accepts_8<native::simd<std::uint32_t, 2, (arch_8 & native::isa(native::arm_feature::crc))>, native::simd<std::uint8_t, 8, arch_8>, native::simd<std::uint8_t, 16, arch_8>>);
  constexpr auto arch_9 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_9 = requires(A... a) { native::udot<arch_9>(a...); };
  static_assert(accepts_9<native::simd<std::uint32_t, 4, arch_9>, native::simd<std::uint8_t, 16, arch_9>, native::simd<std::uint8_t, 16, arch_9>>);
  static_assert(!accepts_9<native::simd<std::int32_t, 4, arch_9>, native::simd<std::uint8_t, 16, arch_9>, native::simd<std::uint8_t, 16, arch_9>>);
  static_assert(std::same_as<decltype(native::udot<arch_9>(std::declval<native::simd<std::uint32_t, 4, arch_9>>(), std::declval<native::simd<std::uint8_t, 16, arch_9>>(), std::declval<native::simd<std::uint8_t, 16, arch_9>>())), native::simd<std::uint32_t, 4, arch_9>>);
  static_assert(!accepts_9<uint32x4_t, uint8x16_t, uint8x16_t>);
  static_assert(!accepts_9<native::simd<std::uint32_t, 4, (arch_9 & native::isa(native::arm_feature::crc))>, native::simd<std::uint8_t, 16, arch_9>, native::simd<std::uint8_t, 16, arch_9>>);
  constexpr auto arch_10 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_10 = requires(A... a) { native::udot_lane<arch_10, 0>(a...); };
  static_assert(accepts_10<native::simd<std::uint32_t, 4, arch_10>, native::simd<std::uint8_t, 16, arch_10>, native::simd<std::uint8_t, 8, arch_10>>);
  static_assert(!accepts_10<native::simd<std::int32_t, 4, arch_10>, native::simd<std::uint8_t, 16, arch_10>, native::simd<std::uint8_t, 8, arch_10>>);
  static_assert(std::same_as<decltype(native::udot_lane<arch_10, 0>(std::declval<native::simd<std::uint32_t, 4, arch_10>>(), std::declval<native::simd<std::uint8_t, 16, arch_10>>(), std::declval<native::simd<std::uint8_t, 8, arch_10>>())), native::simd<std::uint32_t, 4, arch_10>>);
  static_assert(!accepts_10<uint32x4_t, uint8x16_t, uint8x8_t>);
  static_assert(!accepts_10<native::simd<std::uint32_t, 4, (arch_10 & native::isa(native::arm_feature::crc))>, native::simd<std::uint8_t, 16, arch_10>, native::simd<std::uint8_t, 8, arch_10>>);
  constexpr auto arch_11 = native::feature_closure(native::isa(native::arm_feature::dotprod));
  template<class... A> concept accepts_11 = requires(A... a) { native::udot_lane<arch_11, 0>(a...); };
  static_assert(accepts_11<native::simd<std::uint32_t, 4, arch_11>, native::simd<std::uint8_t, 16, arch_11>, native::simd<std::uint8_t, 16, arch_11>>);
  static_assert(!accepts_11<native::simd<std::int32_t, 4, arch_11>, native::simd<std::uint8_t, 16, arch_11>, native::simd<std::uint8_t, 16, arch_11>>);
  static_assert(std::same_as<decltype(native::udot_lane<arch_11, 0>(std::declval<native::simd<std::uint32_t, 4, arch_11>>(), std::declval<native::simd<std::uint8_t, 16, arch_11>>(), std::declval<native::simd<std::uint8_t, 16, arch_11>>())), native::simd<std::uint32_t, 4, arch_11>>);
  static_assert(!accepts_11<uint32x4_t, uint8x16_t, uint8x16_t>);
  static_assert(!accepts_11<native::simd<std::uint32_t, 4, (arch_11 & native::isa(native::arm_feature::crc))>, native::simd<std::uint8_t, 16, arch_11>, native::simd<std::uint8_t, 16, arch_11>>);
}
