// SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
#pragma once
#include <cstdint>
// Preserve the instruction oracle's register inputs while exercising the public simd API.
namespace dotprod_api {
  template<native::isa<native::arm> Arch> requires requires(native::simd<std::int32_t, 2, native::feature_closure(Arch)> accumulator, native::simd<std::int8_t, 8, native::feature_closure(Arch)> lhs, native::simd<std::int8_t, 8, native::feature_closure(Arch)> rhs) { native::sdot<native::feature_closure(Arch)>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  int32x2_t sdot(int32x2_t accumulator, int8x8_t lhs, int8x8_t rhs) noexcept {
    return vget_low_s32(__builtin_bit_cast(int32x4_t, (native::sdot<native::feature_closure(Arch)>(native::simd<std::int32_t, 2, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int32_t, 2, native::feature_closure(Arch)>::native_type, vcombine_s32(accumulator, vdup_n_s32(0)))), native::simd<std::int8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 8, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::int8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 8, native::feature_closure(Arch)>::native_type, rhs)))).to_native()));
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::int32_t, 2, native::feature_closure(Arch)> accumulator, native::simd<std::int8_t, 8, native::feature_closure(Arch)> lhs, native::simd<std::int8_t, 8, native::feature_closure(Arch)> rhs) { native::sdot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  int32x2_t sdot_lane(int32x2_t accumulator, int8x8_t lhs, int8x8_t rhs) noexcept {
    return vget_low_s32(__builtin_bit_cast(int32x4_t, (native::sdot_lane<native::feature_closure(Arch), Lane>(native::simd<std::int32_t, 2, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int32_t, 2, native::feature_closure(Arch)>::native_type, vcombine_s32(accumulator, vdup_n_s32(0)))), native::simd<std::int8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 8, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::int8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 8, native::feature_closure(Arch)>::native_type, rhs)))).to_native()));
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::int32_t, 2, native::feature_closure(Arch)> accumulator, native::simd<std::int8_t, 8, native::feature_closure(Arch)> lhs, native::simd<std::int8_t, 16, native::feature_closure(Arch)> rhs) { native::sdot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  int32x2_t sdot_lane(int32x2_t accumulator, int8x8_t lhs, int8x16_t rhs) noexcept {
    return vget_low_s32(__builtin_bit_cast(int32x4_t, (native::sdot_lane<native::feature_closure(Arch), Lane>(native::simd<std::int32_t, 2, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int32_t, 2, native::feature_closure(Arch)>::native_type, vcombine_s32(accumulator, vdup_n_s32(0)))), native::simd<std::int8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 8, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::int8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 16, native::feature_closure(Arch)>::native_type, rhs)))).to_native()));
  }
  template<native::isa<native::arm> Arch> requires requires(native::simd<std::int32_t, 4, native::feature_closure(Arch)> accumulator, native::simd<std::int8_t, 16, native::feature_closure(Arch)> lhs, native::simd<std::int8_t, 16, native::feature_closure(Arch)> rhs) { native::sdot<native::feature_closure(Arch)>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  int32x4_t sdot(int32x4_t accumulator, int8x16_t lhs, int8x16_t rhs) noexcept {
    return __builtin_bit_cast(int32x4_t, (native::sdot<native::feature_closure(Arch)>(native::simd<std::int32_t, 4, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int32_t, 4, native::feature_closure(Arch)>::native_type, accumulator)), native::simd<std::int8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 16, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::int8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 16, native::feature_closure(Arch)>::native_type, rhs)))).to_native());
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::int32_t, 4, native::feature_closure(Arch)> accumulator, native::simd<std::int8_t, 16, native::feature_closure(Arch)> lhs, native::simd<std::int8_t, 8, native::feature_closure(Arch)> rhs) { native::sdot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  int32x4_t sdot_lane(int32x4_t accumulator, int8x16_t lhs, int8x8_t rhs) noexcept {
    return __builtin_bit_cast(int32x4_t, (native::sdot_lane<native::feature_closure(Arch), Lane>(native::simd<std::int32_t, 4, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int32_t, 4, native::feature_closure(Arch)>::native_type, accumulator)), native::simd<std::int8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 16, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::int8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 8, native::feature_closure(Arch)>::native_type, rhs)))).to_native());
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::int32_t, 4, native::feature_closure(Arch)> accumulator, native::simd<std::int8_t, 16, native::feature_closure(Arch)> lhs, native::simd<std::int8_t, 16, native::feature_closure(Arch)> rhs) { native::sdot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  int32x4_t sdot_lane(int32x4_t accumulator, int8x16_t lhs, int8x16_t rhs) noexcept {
    return __builtin_bit_cast(int32x4_t, (native::sdot_lane<native::feature_closure(Arch), Lane>(native::simd<std::int32_t, 4, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int32_t, 4, native::feature_closure(Arch)>::native_type, accumulator)), native::simd<std::int8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 16, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::int8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::int8_t, 16, native::feature_closure(Arch)>::native_type, rhs)))).to_native());
  }
  template<native::isa<native::arm> Arch> requires requires(native::simd<std::uint32_t, 2, native::feature_closure(Arch)> accumulator, native::simd<std::uint8_t, 8, native::feature_closure(Arch)> lhs, native::simd<std::uint8_t, 8, native::feature_closure(Arch)> rhs) { native::udot<native::feature_closure(Arch)>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  uint32x2_t udot(uint32x2_t accumulator, uint8x8_t lhs, uint8x8_t rhs) noexcept {
    return vget_low_u32(__builtin_bit_cast(uint32x4_t, (native::udot<native::feature_closure(Arch)>(native::simd<std::uint32_t, 2, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint32_t, 2, native::feature_closure(Arch)>::native_type, vcombine_u32(accumulator, vdup_n_u32(0)))), native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::native_type, rhs)))).to_native()));
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::uint32_t, 2, native::feature_closure(Arch)> accumulator, native::simd<std::uint8_t, 8, native::feature_closure(Arch)> lhs, native::simd<std::uint8_t, 8, native::feature_closure(Arch)> rhs) { native::udot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  uint32x2_t udot_lane(uint32x2_t accumulator, uint8x8_t lhs, uint8x8_t rhs) noexcept {
    return vget_low_u32(__builtin_bit_cast(uint32x4_t, (native::udot_lane<native::feature_closure(Arch), Lane>(native::simd<std::uint32_t, 2, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint32_t, 2, native::feature_closure(Arch)>::native_type, vcombine_u32(accumulator, vdup_n_u32(0)))), native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::native_type, rhs)))).to_native()));
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::uint32_t, 2, native::feature_closure(Arch)> accumulator, native::simd<std::uint8_t, 8, native::feature_closure(Arch)> lhs, native::simd<std::uint8_t, 16, native::feature_closure(Arch)> rhs) { native::udot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  uint32x2_t udot_lane(uint32x2_t accumulator, uint8x8_t lhs, uint8x16_t rhs) noexcept {
    return vget_low_u32(__builtin_bit_cast(uint32x4_t, (native::udot_lane<native::feature_closure(Arch), Lane>(native::simd<std::uint32_t, 2, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint32_t, 2, native::feature_closure(Arch)>::native_type, vcombine_u32(accumulator, vdup_n_u32(0)))), native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::native_type, rhs)))).to_native()));
  }
  template<native::isa<native::arm> Arch> requires requires(native::simd<std::uint32_t, 4, native::feature_closure(Arch)> accumulator, native::simd<std::uint8_t, 16, native::feature_closure(Arch)> lhs, native::simd<std::uint8_t, 16, native::feature_closure(Arch)> rhs) { native::udot<native::feature_closure(Arch)>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  uint32x4_t udot(uint32x4_t accumulator, uint8x16_t lhs, uint8x16_t rhs) noexcept {
    return __builtin_bit_cast(uint32x4_t, (native::udot<native::feature_closure(Arch)>(native::simd<std::uint32_t, 4, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint32_t, 4, native::feature_closure(Arch)>::native_type, accumulator)), native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::native_type, rhs)))).to_native());
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::uint32_t, 4, native::feature_closure(Arch)> accumulator, native::simd<std::uint8_t, 16, native::feature_closure(Arch)> lhs, native::simd<std::uint8_t, 8, native::feature_closure(Arch)> rhs) { native::udot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  uint32x4_t udot_lane(uint32x4_t accumulator, uint8x16_t lhs, uint8x8_t rhs) noexcept {
    return __builtin_bit_cast(uint32x4_t, (native::udot_lane<native::feature_closure(Arch), Lane>(native::simd<std::uint32_t, 4, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint32_t, 4, native::feature_closure(Arch)>::native_type, accumulator)), native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 8, native::feature_closure(Arch)>::native_type, rhs)))).to_native());
  }
  template<native::isa<native::arm> Arch, int Lane> requires requires(native::simd<std::uint32_t, 4, native::feature_closure(Arch)> accumulator, native::simd<std::uint8_t, 16, native::feature_closure(Arch)> lhs, native::simd<std::uint8_t, 16, native::feature_closure(Arch)> rhs) { native::udot_lane<native::feature_closure(Arch), Lane>(accumulator, lhs, rhs); }
  inline __attribute__((always_inline, target("dotprod")))
  uint32x4_t udot_lane(uint32x4_t accumulator, uint8x16_t lhs, uint8x16_t rhs) noexcept {
    return __builtin_bit_cast(uint32x4_t, (native::udot_lane<native::feature_closure(Arch), Lane>(native::simd<std::uint32_t, 4, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint32_t, 4, native::feature_closure(Arch)>::native_type, accumulator)), native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::native_type, lhs)), native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::from_native(__builtin_bit_cast(typename native::simd<std::uint8_t, 16, native::feature_closure(Arch)>::native_type, rhs)))).to_native());
  }
  template<native::isa<native::arm> Arch, class... A>
  void sdot(A...) = delete;
  template<native::isa<native::arm> Arch, int Lane, class... A>
  void sdot_lane(A...) = delete;
  template<native::isa<native::arm> Arch, class... A>
  void udot(A...) = delete;
  template<native::isa<native::arm> Arch, int Lane, class... A>
  void udot_lane(A...) = delete;
}
