# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
# Inspect real producer/consumer commands, including regenerated installed BMIs.
file(READ "${BUILD_DIR}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count}-1")
set(saw_minimal FALSE)
set(saw_native FALSE)
set(saw_dispatcher FALSE)
foreach(index RANGE 0 ${last})
  string(JSON source GET "${commands}" ${index} file)
  string(JSON command GET "${commands}" ${index} command)
  string(REPLACE "\\" "/" source "${source}")
  if(source MATCHES "native[.]scalar[.]ccm$")
    set(saw_minimal TRUE)
    if(command MATCHES "cmake_pch|/Yu|/Fp")
      message(FATAL_ERROR "Common module provider uses PCH: ${command}")
    endif()
  elseif(source MATCHES "native([.]simd)?[.]ccm$")
    set(saw_native TRUE)
    if(command MATCHES "cmake_pch|/Yu|/Fp")
      message(FATAL_ERROR "Hub provider must not use a PCH: ${command}")
    endif()
  elseif(source MATCHES "avx512_fp16/main[.]cc$")
    set(saw_dispatcher TRUE)
  else()
    continue()
  endif()
  # These definitions come from actual probes of the configured minimum.
  # Stronger minimum ABIs are allowed; optional producer flags must not leak.
  foreach(feature AVX512_FP16 AVX512_BF16)
    if(feature STREQUAL "AVX512_FP16")
      set(option "mavx512fp16")
    else()
      set(option "mavx512bf16")
    endif()
    if(command MATCHES "NATIVE_MINIMAL_HAS_${feature}=0" AND command MATCHES "${option}")
      message(FATAL_ERROR "Optional feature leaked into baseline: ${command}")
    endif()
  endforeach()
endforeach()
# CMake omits synthetic installed BMI commands from compile_commands.json.
# Read their actual Ninja command graph rather than assuming them absent.
if(NOT saw_minimal OR NOT saw_native)
  file(STRINGS "${BUILD_DIR}/build.ninja" bmi_edges REGEX "^build .*\\.bmi: ")
  set(bmi_targets)
  foreach(edge IN LISTS bmi_edges)
    string(REGEX REPLACE "^build (.+[.]bmi): .*" "\\1" target "${edge}")
    string(REPLACE "$ " " " target "${target}")
    string(REPLACE "$:" ":" target "${target}")
    string(REPLACE "$$" "$" target "${target}")
    list(APPEND bmi_targets "${target}")
  endforeach()
  execute_process(COMMAND "${NINJA}" -C "${BUILD_DIR}" -t commands ${bmi_targets}
    RESULT_VARIABLE status OUTPUT_VARIABLE graph ERROR_VARIABLE errors)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Cannot inspect installed BMI commands: ${errors}")
  endif()
  string(REPLACE "\n" ";" lines "${graph}")
  foreach(command IN LISTS lines)
    if(NOT command MATCHES "--precompile")
      continue()
    endif()
    if(command MATCHES "native[.]scalar[.]ccm")
      set(saw_minimal TRUE)
      foreach(feature FP16 BF16)
        string(TOLOWER "${feature}" lower)
        if(command MATCHES "NATIVE_MINIMAL_HAS_AVX512_${feature}=0" AND command MATCHES "mavx512${lower}")
          message(FATAL_ERROR "Optional feature leaked into common BMI: ${command}")
        endif()
      endforeach()
    elseif(command MATCHES "native([.]simd)?[.]ccm")
      set(saw_native TRUE)
      foreach(feature FP16 BF16)
        string(TOLOWER "${feature}" lower)
        if(command MATCHES "NATIVE_MINIMAL_HAS_AVX512_${feature}=0" AND command MATCHES "mavx512${lower}")
          message(FATAL_ERROR "Optional feature leaked into hub BMI: ${command}")
        endif()
      endforeach()
    else()
      continue()
    endif()
    if(command MATCHES "cmake_pch|/Yu|/Fp")
      message(FATAL_ERROR "Synthetic module provider uses PCH: ${command}")
    endif()
  endforeach()
endif()
if(NOT saw_minimal OR NOT saw_native OR NOT saw_dispatcher)
  message(FATAL_ERROR "Missing compile commands for common/native/dispatcher boundaries")
endif()
message(STATUS "Hub and common providers compile without PCH; optional ISA flags stay out of the baseline")
