# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
# Check effective optional-instruction availability in the dispatcher's exact
# compilation environment. AArch64 macro definitions alone can be misleading.
file(READ "${BUILD_DIR}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count}-1")
cmake_path(NORMAL_PATH SOURCE)
set(found FALSE)
foreach(index RANGE 0 ${last})
  string(JSON file GET "${commands}" ${index} file)
  cmake_path(NORMAL_PATH file)
  if(NOT file STREQUAL SOURCE)
    continue()
  endif()
  set(found TRUE)
  string(JSON command GET "${commands}" ${index} command)
  string(JSON directory GET "${commands}" ${index} directory)
  if(NOT command MATCHES "NATIVE_MINIMAL_HAS_NEON_BF16=([01])")
    message(FATAL_ERROR "Dispatcher has no exported minimum feature result: ${command}")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  file(MAKE_DIRECTORY "${BUILD_DIR}/bf16-baseline-probe")
  set(probe "${BUILD_DIR}/bf16-baseline-probe/probe.cc")
  file(WRITE "${probe}" "#include <arm_neon.h>\nfloat32x4_t probe(float32x4_t c,bfloat16x8_t a,bfloat16x8_t b) { return vbfdotq_f32(c,a,b); }\n")
  separate_arguments(arguments NATIVE_COMMAND "${command}")
  list(GET arguments 0 compiler)
  set(msvc_frontend FALSE)
  if(compiler MATCHES "clang-cl([.]exe)?$")
    set(msvc_frontend TRUE)
  endif()
  set(rewritten)
  set(output_next FALSE)
  set(discard_next FALSE)
  foreach(argument IN LISTS arguments)
    file(TO_CMAKE_PATH "${argument}" normalized)
    if(discard_next)
      set(discard_next FALSE)
    elseif((NOT msvc_frontend AND argument MATCHES "^-(M|MM|MD|MMD|MP|MG)$") OR
        argument MATCHES "^[-/]clang:-(M|MM|MD|MMD|MP|MG)$")
      # In clang-cl, bare -MD/-MT (and debug suffixes) select the CRT and stay.
    elseif((NOT msvc_frontend AND argument MATCHES "^-M[FQTJ]$") OR
        argument MATCHES "^[-/]clang:-M[FQTJ]$" OR argument STREQUAL "-serialize-diagnostics")
      set(discard_next TRUE)
    elseif((NOT msvc_frontend AND argument MATCHES "^-M[FQTJ].+") OR
        argument MATCHES "^[-/]clang:-M[FQTJ].+")
      # Attached dependency-output paths are discarded as well.
    elseif(argument MATCHES "^[-/]Fd")
      list(APPEND rewritten "/Fd${BUILD_DIR}/bf16-baseline-probe/probe.pdb")
    elseif(output_next)
      list(APPEND rewritten "${BUILD_DIR}/bf16-baseline-probe/probe.o")
      set(output_next FALSE)
    elseif(argument STREQUAL "-o")
      list(APPEND rewritten "-o")
      set(output_next TRUE)
    elseif(argument MATCHES "^/Fo")
      list(APPEND rewritten "/Fo${BUILD_DIR}/bf16-baseline-probe/probe.obj")
    elseif(argument MATCHES "^@.*[.]modmap$")
      # The standalone intrinsic probe imports no C++ named modules.
    elseif(normalized STREQUAL SOURCE)
      list(APPEND rewritten "${probe}")
    else()
      list(APPEND rewritten "${argument}")
    endif()
  endforeach()
  execute_process(COMMAND ${rewritten} WORKING_DIRECTORY "${directory}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(expected AND NOT result EQUAL 0)
    message(FATAL_ERROR "Dispatcher lost minimum BF16 support: ${output}${errors}")
  elseif(NOT expected AND result EQUAL 0)
    message(FATAL_ERROR "Optional BF16 flags leaked into the minimum dispatcher: ${command}")
  elseif(NOT expected AND NOT errors MATCHES "bf16")
    message(FATAL_ERROR "Probe failed for an unrelated reason: ${output}${errors}")
  endif()
  message(STATUS "Dispatcher effective BF16 availability matches minimum: ${expected}")
endforeach()
if(NOT found)
  message(FATAL_ERROR "Dispatcher compile command not found for ${SOURCE}")
endif()
